// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

private let builtInAttributedStringSynchronous: @convention(thin) (BuiltInResultInvocation) -> AttributedString =
    { invocation in invocation.call(returning: AttributedString.self) as! AttributedString }

private let builtInAttributedStringSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> AttributedString =
    { invocation in try invocation.callThrowing(returning: AttributedString.self) as! AttributedString }

private let builtInAttributedStringAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> AttributedString =
    { invocation in await invocation.call() as! AttributedString }

private let builtInAttributedStringAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> AttributedString =
    { invocation in try await invocation.callThrowing() as! AttributedString }

extension BuiltInResultAdapters {
    static func appendAttributedString(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        append(
            returning: AttributedString.self,
            resultTransport: .indirect,
            synchronous: token(for: builtInAttributedStringSynchronous),
            synchronousThrowing: token(for: builtInAttributedStringSynchronousThrowing),
            asynchronous: token(for: builtInAttributedStringAsynchronous),
            asynchronousThrowing: token(for: builtInAttributedStringAsynchronousThrowing),
            to: &adapters
        )
    }
}
// swiftlint:enable force_cast
