// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

private let builtInCharacterSetSynchronous: @convention(thin) (BuiltInResultInvocation) -> CharacterSet =
    { invocation in invocation.call(returning: CharacterSet.self) as! CharacterSet }

private let builtInCharacterSetSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> CharacterSet =
    { invocation in try invocation.callThrowing(returning: CharacterSet.self) as! CharacterSet }

private let builtInCharacterSetAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> CharacterSet =
    { invocation in await invocation.call() as! CharacterSet }

private let builtInCharacterSetAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> CharacterSet =
    { invocation in try await invocation.callThrowing() as! CharacterSet }

extension BuiltInResultAdapters {
    static func appendCharacterSet(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        append(
            returning: CharacterSet.self,
            resultTransport: .indirect,
            synchronous: token(for: builtInCharacterSetSynchronous),
            synchronousThrowing: token(for: builtInCharacterSetSynchronousThrowing),
            asynchronous: token(for: builtInCharacterSetAsynchronous),
            asynchronousThrowing: token(for: builtInCharacterSetAsynchronousThrowing),
            to: &adapters
        )
    }
}
// swiftlint:enable force_cast
