// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

private let builtInDateSynchronous: @convention(thin) (BuiltInResultInvocation) -> Date =
    { invocation in invocation.call(returning: Date.self) as! Date }

private let builtInDateSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Date =
    { invocation in try invocation.callThrowing(returning: Date.self) as! Date }

private let builtInDateAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> Date =
    { invocation in await invocation.call() as! Date }

private let builtInDateAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Date =
    { invocation in try await invocation.callThrowing() as! Date }

extension BuiltInResultAdapters {
    static func appendDate(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        append(
            returning: Date.self,
            resultTransport: .indirect,
            synchronous: token(for: builtInDateSynchronous),
            synchronousThrowing: token(for: builtInDateSynchronousThrowing),
            asynchronous: token(for: builtInDateAsynchronous),
            asynchronousThrowing: token(for: builtInDateAsynchronousThrowing),
            to: &adapters
        )
    }
}
// swiftlint:enable force_cast
