// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

private let builtInIndexSetSynchronous: @convention(thin) (BuiltInResultInvocation) -> IndexSet =
    { invocation in invocation.call(returning: IndexSet.self) as! IndexSet }

private let builtInIndexSetSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> IndexSet =
    { invocation in try invocation.callThrowing(returning: IndexSet.self) as! IndexSet }

private let builtInIndexSetAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> IndexSet =
    { invocation in await invocation.call() as! IndexSet }

private let builtInIndexSetAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> IndexSet =
    { invocation in try await invocation.callThrowing() as! IndexSet }

extension BuiltInResultAdapters {
    static func appendIndexSet(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        append(
            returning: IndexSet.self,
            resultTransport: .indirect,
            synchronous: token(for: builtInIndexSetSynchronous),
            synchronousThrowing: token(for: builtInIndexSetSynchronousThrowing),
            asynchronous: token(for: builtInIndexSetAsynchronous),
            asynchronousThrowing: token(for: builtInIndexSetAsynchronousThrowing),
            to: &adapters
        )
    }
}
// swiftlint:enable force_cast
