// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

#if (!os(WASI)) && compiler(>=6.4)
    private let builtInPersonNameComponentsSynchronous: @convention(thin) (BuiltInResultInvocation) -> PersonNameComponents =
        { invocation in invocation.call(returning: PersonNameComponents.self) as! PersonNameComponents }

    private let builtInPersonNameComponentsSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> PersonNameComponents =
        { invocation in try invocation.callThrowing(returning: PersonNameComponents.self) as! PersonNameComponents }

    private let builtInPersonNameComponentsAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> PersonNameComponents =
        { invocation in await invocation.call() as! PersonNameComponents }

    private let builtInPersonNameComponentsAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> PersonNameComponents =
        { invocation in try await invocation.callThrowing() as! PersonNameComponents }
#endif

extension BuiltInResultAdapters {
    #if (!os(WASI)) && compiler(>=6.4)
        static func appendPersonNameComponents(
            to adapters: inout [RuntimeAutomaticRequirementAdapter]
        ) {
            append(
                returning: PersonNameComponents.self,
                resultTransport: .indirect,
                synchronous: token(for: builtInPersonNameComponentsSynchronous),
                synchronousThrowing: token(for: builtInPersonNameComponentsSynchronousThrowing),
                asynchronous: token(for: builtInPersonNameComponentsAsynchronous),
                asynchronousThrowing: token(for: builtInPersonNameComponentsAsynchronousThrowing),
                to: &adapters
            )
        }
    #endif
}
// swiftlint:enable force_cast
