// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

private let builtInURLSynchronous: @convention(thin) (BuiltInResultInvocation) -> URL =
    { invocation in invocation.call(returning: URL.self) as! URL }

private let builtInURLSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> URL =
    { invocation in try invocation.callThrowing(returning: URL.self) as! URL }

private let builtInURLAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> URL =
    { invocation in await invocation.call() as! URL }

private let builtInURLAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> URL =
    { invocation in try await invocation.callThrowing() as! URL }

extension BuiltInResultAdapters {
    static func appendURL(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        append(
            returning: URL.self,
            resultTransport: .indirect,
            synchronous: token(for: builtInURLSynchronous),
            synchronousThrowing: token(for: builtInURLSynchronousThrowing),
            asynchronous: token(for: builtInURLAsynchronous),
            asynchronousThrowing: token(for: builtInURLAsynchronousThrowing),
            to: &adapters
        )
    }
}
// swiftlint:enable force_cast
