// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

#if (canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))) && compiler(>=6.3.3)
    private let builtInURLRequestSynchronous: @convention(thin) (BuiltInResultInvocation) -> URLRequest =
        { invocation in invocation.call(returning: URLRequest.self) as! URLRequest }

    private let builtInURLRequestSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> URLRequest =
        { invocation in try invocation.callThrowing(returning: URLRequest.self) as! URLRequest }

    private let builtInURLRequestAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> URLRequest =
        { invocation in await invocation.call() as! URLRequest }

    private let builtInURLRequestAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> URLRequest =
        { invocation in try await invocation.callThrowing() as! URLRequest }
#endif

extension BuiltInResultAdapters {
    #if (canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))) && compiler(>=6.3.3)
        static func appendURLRequest(
            to adapters: inout [RuntimeAutomaticRequirementAdapter]
        ) {
            append(
                returning: URLRequest.self,
                resultTransport: .indirect,
                synchronous: token(for: builtInURLRequestSynchronous),
                synchronousThrowing: token(for: builtInURLRequestSynchronousThrowing),
                asynchronous: token(for: builtInURLRequestAsynchronous),
                asynchronousThrowing: token(for: builtInURLRequestAsynchronousThrowing),
                to: &adapters
            )
        }
    #endif
}
// swiftlint:enable force_cast
