// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

// The catalog fixes the result type for each compiler-typed adapter.
// swiftlint:disable force_cast

#if (!os(WASI)) && compiler(>=6.4)
    private let builtInUUIDSynchronous: @convention(thin) (BuiltInResultInvocation) -> UUID =
        { invocation in invocation.call(returning: UUID.self) as! UUID }

    private let builtInUUIDSynchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> UUID =
        { invocation in try invocation.callThrowing(returning: UUID.self) as! UUID }

    private let builtInUUIDAsynchronous: @convention(thin) (BuiltInResultInvocation) async -> UUID =
        { invocation in await invocation.call() as! UUID }

    private let builtInUUIDAsynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> UUID =
        { invocation in try await invocation.callThrowing() as! UUID }
#endif

extension BuiltInResultAdapters {
    #if (!os(WASI)) && compiler(>=6.4)
        static func appendUUID(
            to adapters: inout [RuntimeAutomaticRequirementAdapter]
        ) {
            append(
                returning: UUID.self,
                resultTransport: .indirect,
                synchronous: token(for: builtInUUIDSynchronous),
                synchronousThrowing: token(for: builtInUUIDSynchronousThrowing),
                asynchronous: token(for: builtInUUIDAsynchronous),
                asynchronousThrowing: token(for: builtInUUIDAsynchronousThrowing),
                to: &adapters
            )
        }
    #endif
}
// swiftlint:enable force_cast
