// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 1 executes every supported effect and sendability branch.

import Testing
import TestDoublesRuntime
import TestDoublesRuntimeMetadata

@Suite
struct DynamicFunctionBridgeArity1Tests {
    @Test
    func untypedArity1Synchronous() async throws {
        let function: (Int) -> Int = { value0 in value0 }
        #expect(
            roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1SendableSynchronous() async throws {
        let function: @Sendable (Int) -> Int = { value0 in value0 }
        #expect(
            roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1Throwing() async throws {
        let function: (Int) throws -> Int = { value0 in value0 }
        #expect(
            try roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1SendableThrowing() async throws {
        let function: @Sendable (Int) throws -> Int = { value0 in value0 }
        #expect(
            try roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1Asynchronous() async throws {
        let function: (Int) async -> Int = {
            value0 in
            await Task.yield()
            return value0
        }
        #expect(
            await roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1SendableAsynchronous() async throws {
        let function: @Sendable (Int) async -> Int = {
            value0 in
            await Task.yield()
            return value0
        }
        #expect(
            await roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1AsynchronousThrowing() async throws {
        let function: (Int) async throws -> Int = {
            value0 in
            await Task.yield()
            return value0
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @Test
    func untypedArity1SendableAsynchronousThrowing() async throws {
        let function: @Sendable (Int) async throws -> Int = {
            value0 in
            await Task.yield()
            return value0
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1)
                == 1
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity1TypedThrowing() async throws {
        let function: (Int) throws(GeneratedBridgeMatrixError) -> Int = { value0 in value0 }
        #if os(Linux) && arch(x86_64)
            let functionType = type(of: function)
            #expect(
                FunctionReabstraction.automaticResultUnsupportedReason(
                    for: functionType
                )?.contains("Typed-throws closure values are unavailable on Linux x86_64") == true
            )
        #else
            #expect(
                try roundTripGeneratedBridge(function)(1)
                    == 1
            )
        #endif
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity1SendableTypedThrowing() async throws {
        let function: @Sendable (Int) throws(GeneratedBridgeMatrixError) -> Int = { value0 in value0 }
        #if os(Linux) && arch(x86_64)
            let functionType = type(of: function)
            #expect(
                FunctionReabstraction.automaticResultUnsupportedReason(
                    for: functionType
                )?.contains("Typed-throws closure values are unavailable on Linux x86_64") == true
            )
        #else
            #expect(
                try roundTripGeneratedBridge(function)(1)
                    == 1
            )
        #endif
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity1AsynchronousTypedThrowing() async throws {
        let function: (Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0 in
            await Task.yield()
            return value0
        }
        #if os(Linux) && arch(x86_64)
            let functionType = type(of: function)
            #expect(
                FunctionReabstraction.automaticResultUnsupportedReason(
                    for: functionType
                )?.contains("Typed-throws closure values are unavailable on Linux x86_64") == true
            )
        #else
            #expect(
                try await roundTripGeneratedBridge(function)(1)
                    == 1
            )
        #endif
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity1SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable (Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0 in
            await Task.yield()
            return value0
        }
        #if os(Linux) && arch(x86_64)
            let functionType = type(of: function)
            #expect(
                FunctionReabstraction.automaticResultUnsupportedReason(
                    for: functionType
                )?.contains("Typed-throws closure values are unavailable on Linux x86_64") == true
            )
        #else
            #expect(
                try await roundTripGeneratedBridge(function)(1)
                    == 1
            )
        #endif
    }
}
