import Foundation

package struct ManualStubBatchGenerator {
    package struct Source: Sendable {
        package let identifier: String
        package let contents: String
        /// The module declaring these protocols when it is not the module
        /// compiling the generated file. Generated code imports it with
        /// `@testable`, and its `private` protocols are skipped.
        package let module: String?

        package init(identifier: String, contents: String, module: String? = nil) {
            self.identifier = identifier
            self.contents = contents
            self.module = module
        }
    }

    package struct SkippedProtocol: Sendable {
        package let name: String
        package let sourceIdentifier: String
        package let reason: String
    }

    package struct Result: Sendable {
        package let source: String
        package let generatedProtocolNames: [String]
        package let skippedProtocols: [SkippedProtocol]
    }

    private let sources: [Source]
    private let additionalImports: [String]

    /// - Parameters:
    ///   - sources: The Swift sources to scan for protocols.
    ///   - additionalImports: Import declarations the generated file needs,
    ///     such as `@testable import App`.
    package init(sources: [Source], additionalImports: [String] = []) {
        self.sources = sources
        self.additionalImports = additionalImports
    }

    package func render(importingTestDoubles: Bool = true) throws -> Result {
        var generated = [(name: String, source: String)]()
        var skipped = [SkippedProtocol]()
        var declaringSourceByProtocol = [String: String]()

        let knownProtocols = Dictionary(
            sources.flatMap { SwiftProtocolDeclarationScanner(source: $0.contents).declarations() }
                .map { ($0.name, $0) },
            uniquingKeysWith: { first, _ in first }
        )
        for input in sources.sorted(by: { $0.identifier < $1.identifier }) {
            let declarations = SwiftProtocolDeclarationScanner(source: input.contents)
                .declarations()
            for declaration in declarations {
                // Another module's private protocol is not visible here.
                if input.module != nil, declaration.isFilePrivate(in: input.contents) {
                    continue
                }
                if let previousSource = declaringSourceByProtocol[declaration.name] {
                    throw ManualStubGeneratorError.duplicateProtocol(
                        name: declaration.name,
                        firstSource: previousSource,
                        secondSource: input.identifier
                    )
                }
                declaringSourceByProtocol[declaration.name] = input.identifier

                do {
                    let source = try ManualStubGenerator(
                        protocolName: declaration.name,
                        source: input.contents,
                        knownProtocols: knownProtocols
                    ).render(
                        importingTestDoubles: false,
                        preservingSourceImports: false
                    )
                    generated.append((declaration.name, source))
                } catch let error as ManualStubGeneratorError {
                    skipped.append(
                        SkippedProtocol(
                            name: declaration.name,
                            sourceIdentifier: input.identifier,
                            reason: error.localizedDescription
                        )
                    )
                }
            }
        }

        guard generated.isEmpty == false else {
            throw ManualStubGeneratorError.noEligibleProtocols
        }

        let header = "// Generated by ManualStubGeneratorTool; do not edit by hand.\n"
        var imports = sourceImportLines()
        let generatedModules = Set(
            sources.filter { source in
                generated.contains { entry in
                    declaringSourceByProtocol[entry.name] == source.identifier
                }
            }.compactMap(\.module)
        )
        for module in generatedModules.sorted() {
            appendImport("@testable import \(module)", to: &imports)
        }
        for line in additionalImports {
            appendImport(line, to: &imports)
        }
        if importingTestDoubles, imports.contains("import TestDoubles") == false {
            imports.append("import TestDoubles")
        }
        let importBlock = imports.isEmpty ? "" : "\n" + imports.joined(separator: "\n") + "\n"
        let declarations = generated.map(\.source).joined(separator: "\n")
        return Result(
            source: "\(header)\(importBlock)\n\(declarations)",
            generatedProtocolNames: generated.map(\.name),
            skippedProtocols: skipped
        )
    }

    /// Appends `line` unless the same module is already imported, keeping
    /// the `@testable` form when either spelling asks for it.
    private func appendImport(_ line: String, to imports: inout [String]) {
        let module = line.split(separator: " ").last.map(String.init) ?? line
        if let existing = imports.firstIndex(where: {
            $0.split(separator: " ").last.map(String.init) == module
        }) {
            if line.hasPrefix("@testable") { imports[existing] = line }
            return
        }
        imports.append(line)
    }

    private func sourceImportLines() -> [String] {
        var seen: Set<String> = []
        return sources.sorted(by: { $0.identifier < $1.identifier }).flatMap { source in
            source.contents.split(separator: "\n").compactMap { line in
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                guard
                    trimmed.hasPrefix("import ")
                        || trimmed.hasPrefix("@testable import ")
                        || trimmed.hasPrefix("@preconcurrency import ")
                        || trimmed.hasPrefix("@_exported import ")
                else {
                    return nil
                }
                guard seen.insert(trimmed).inserted else { return nil }
                return trimmed
            }
        }
    }
}

struct SwiftProtocolDeclaration {
    let name: String
    let body: String
    let inheritedTypeNames: [String]
    var primaryAssociatedTypeNames: [String] = []
    /// Attribute names written before `protocol`, without `@`.
    var attributes: [String] = []

    var inheritsActor: Bool {
        inheritedTypeNames.contains("Actor")
    }

    /// Whether the declaration itself restricts conformers to classes.
    var isClassBound: Bool {
        inheritedTypeNames.contains("AnyObject") || inheritedTypeNames.contains("class")
    }

    /// Whether the protocol is declared `private` or `fileprivate`.
    func isFilePrivate(in source: String) -> Bool {
        let normalized = source.split(whereSeparator: \.isWhitespace).joined(separator: " ")
        return normalized.contains("private protocol \(name)")
    }

    /// The global actor isolating the protocol, such as `MainActor`.
    var globalActor: String? {
        attributes.first { $0 == "MainActor" || ($0.hasSuffix("Actor") && $0 != "Actor") }
    }
}

struct SwiftProtocolDeclarationScanner {
    private struct Token {
        enum Kind: Equatable {
            case identifier
            case punctuation(Character)
        }

        let kind: Kind
        let text: String
        let range: Range<String.Index>
    }

    let source: String

    func declarations() -> [SwiftProtocolDeclaration] {
        let tokens = tokens()
        var result = [SwiftProtocolDeclaration]()
        var tokenIndex = tokens.startIndex

        while tokenIndex < tokens.endIndex {
            guard
                tokens[tokenIndex].kind == .identifier,
                tokens[tokenIndex].text == "protocol",
                tokens.indices.contains(tokenIndex + 1),
                tokens[tokenIndex + 1].kind == .identifier
            else {
                tokenIndex += 1
                continue
            }

            let name = tokens[tokenIndex + 1].text
            var openingIndex = tokenIndex + 2
            while openingIndex < tokens.endIndex,
                tokens[openingIndex].kind != .punctuation("{")
            {
                openingIndex += 1
            }
            guard openingIndex < tokens.endIndex else {
                tokenIndex += 1
                continue
            }

            let inheritedTypeNames = inheritedTypeNames(
                in: tokens[(tokenIndex + 2) ..< openingIndex]
            )
            let primaryAssociatedTypeNames = primaryAssociatedTypeNames(
                in: tokens[(tokenIndex + 2) ..< openingIndex]
            )
            let attributes = attributeNames(preceding: tokenIndex, in: tokens)

            var depth = 1
            var closingIndex = openingIndex + 1
            while closingIndex < tokens.endIndex, depth > 0 {
                if tokens[closingIndex].kind == .punctuation("{") {
                    depth += 1
                } else if tokens[closingIndex].kind == .punctuation("}") {
                    depth -= 1
                }
                closingIndex += 1
            }
            guard depth == 0 else {
                tokenIndex += 1
                continue
            }

            let closingToken = tokens[closingIndex - 1]
            result.append(
                SwiftProtocolDeclaration(
                    name: name,
                    body: String(
                        source[
                            tokens[openingIndex].range.upperBound
                                ..< closingToken.range.lowerBound
                        ]
                    ),
                    inheritedTypeNames: inheritedTypeNames,
                    primaryAssociatedTypeNames: primaryAssociatedTypeNames,
                    attributes: attributes
                )
            )
            tokenIndex = closingIndex
        }
        return result
    }

    /// Names inside `<...>` directly after the protocol name.
    private func primaryAssociatedTypeNames(
        in header: ArraySlice<Token>
    ) -> [String] {
        guard let first = header.first, first.kind == .punctuation("<"),
            let closing = header.firstIndex(where: { $0.kind == .punctuation(">") })
        else { return [] }
        return header[header.index(after: header.startIndex) ..< closing].compactMap { token in
            token.kind == .identifier ? token.text : nil
        }
    }

    /// Attribute names, such as `MainActor`, written before `protocol`,
    /// skipping access and other declaration modifiers.
    private func attributeNames(preceding index: Int, in tokens: [Token]) -> [String] {
        let modifiers: Set<String> = [
            "public", "package", "internal", "fileprivate", "private", "open", "nonisolated"
        ]
        var attributes = [String]()
        var cursor = index - 1
        while cursor >= tokens.startIndex {
            let token = tokens[cursor]
            if token.kind == .identifier, modifiers.contains(token.text) {
                cursor -= 1
                continue
            }
            if token.kind == .punctuation(")") {
                // Skip attribute arguments, such as `@available(...)`.
                var depth = 0
                var scan = cursor
                while scan >= tokens.startIndex {
                    if tokens[scan].kind == .punctuation(")") { depth += 1 }
                    if tokens[scan].kind == .punctuation("(") {
                        depth -= 1
                        if depth == 0 { break }
                    }
                    scan -= 1
                }
                cursor = scan - 1
                continue
            }
            if token.kind == .identifier, cursor > tokens.startIndex,
                tokens[cursor - 1].kind == .punctuation("@")
            {
                attributes.append(token.text)
                cursor -= 2
                continue
            }
            break
        }
        return attributes.reversed()
    }

    private func inheritedTypeNames(
        in header: ArraySlice<Token>
    ) -> [String] {
        guard let colon = header.firstIndex(where: { $0.kind == .punctuation(":") })
        else { return [] }
        let inheritance = header[header.index(after: colon)...]
            .prefix { token in
                token.kind != .identifier || token.text != "where"
            }
        return inheritance.compactMap { token in
            token.kind == .identifier ? token.text : nil
        }
    }

    private func tokens() -> [Token] {
        var result = [Token]()
        var index = source.startIndex

        while index < source.endIndex {
            let character = source[index]
            if character.isWhitespace {
                index = source.index(after: index)
            } else if character == "/", let next = nextIndex(after: index) {
                if source[next] == "/" {
                    index = endOfLine(startingAt: next)
                } else if source[next] == "*" {
                    index = endOfBlockComment(startingAt: index)
                } else {
                    result.append(punctuationToken(at: index))
                    index = source.index(after: index)
                }
            } else if character == "\"" {
                index = endOfStringLiteral(startingAt: index)
            } else if character == "`" {
                let start = index
                index = source.index(after: index)
                let nameStart = index
                while index < source.endIndex, source[index] != "`" {
                    index = source.index(after: index)
                }
                let name = String(source[nameStart ..< index])
                if index < source.endIndex {
                    index = source.index(after: index)
                }
                result.append(
                    Token(kind: .identifier, text: name, range: start ..< index)
                )
            } else if isIdentifierStart(character) {
                let start = index
                index = source.index(after: index)
                while index < source.endIndex, isIdentifierContinuation(source[index]) {
                    index = source.index(after: index)
                }
                result.append(
                    Token(
                        kind: .identifier,
                        text: String(source[start ..< index]),
                        range: start ..< index
                    )
                )
            } else {
                result.append(punctuationToken(at: index))
                index = source.index(after: index)
            }
        }
        return result
    }

    private func punctuationToken(at index: String.Index) -> Token {
        Token(
            kind: .punctuation(source[index]),
            text: String(source[index]),
            range: index ..< source.index(after: index)
        )
    }

    private func nextIndex(after index: String.Index) -> String.Index? {
        let next = source.index(after: index)
        return next < source.endIndex ? next : nil
    }

    private func endOfLine(startingAt index: String.Index) -> String.Index {
        var index = index
        while index < source.endIndex, source[index].isNewline == false {
            index = source.index(after: index)
        }
        return index
    }

    private func endOfBlockComment(startingAt start: String.Index) -> String.Index {
        var index = source.index(start, offsetBy: 2)
        var depth = 1
        while index < source.endIndex, depth > 0 {
            guard let next = nextIndex(after: index) else {
                return source.endIndex
            }
            if source[index] == "/", source[next] == "*" {
                depth += 1
                index = source.index(after: next)
            } else if source[index] == "*", source[next] == "/" {
                depth -= 1
                index = source.index(after: next)
            } else {
                index = source.index(after: index)
            }
        }
        return index
    }

    private func endOfStringLiteral(startingAt start: String.Index) -> String.Index {
        var index = source.index(after: start)
        var escaped = false
        while index < source.endIndex {
            let character = source[index]
            index = source.index(after: index)
            if escaped {
                escaped = false
            } else if character == "\\" {
                escaped = true
            } else if character == "\"" {
                return index
            }
        }
        return source.endIndex
    }

    private func isIdentifierStart(_ character: Character) -> Bool {
        character == "_" || character.isLetter
    }

    private func isIdentifierContinuation(_ character: Character) -> Bool {
        isIdentifierStart(character) || character.isNumber
    }
}
