// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Shared support for the independently diagnosable fixed-arity suites.

@testable import TestDoubles

enum GeneratedBridgeMatrixError: Error {
    case failure
}

func roundTripGeneratedBridge<Function>(
    _ function: Function
) -> Function {
    let source = ManagedValueBuffer(
        type: Function.self,
        minimumByteCount: 16
    )
    RuntimeValueTransport.initializeDirectValue(
        function,
        expectedType: Function.self,
        to: source.storage
    )
    source.markInitialized()
    let boxed = FunctionReabstraction.boxDirectArgument(
        type: Function.self,
        source: source.storage
    )
    source.destroyInitializedValue()
    guard let result = boxed as? Function else {
        preconditionFailure(
            "[TestDoublesTests] Generated bridge changed the function type."
        )
    }
    return result
}
