// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 0 executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

@Suite
struct DynamicFunctionBridgeArity0Tests {
    @Test
    func untypedArity0Synchronous() async throws {
        let function: () -> Int = { 40 }
        #expect(
            roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0SendableSynchronous() async throws {
        let function: @Sendable () -> Int = { 40 }
        #expect(
            roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0Throwing() async throws {
        let function: () throws -> Int = { 40 }
        #expect(
            try roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0SendableThrowing() async throws {
        let function: @Sendable () throws -> Int = { 40 }
        #expect(
            try roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0Asynchronous() async throws {
        let function: () async -> Int = {
            await Task.yield()
            return 40
        }
        #expect(
            await roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0SendableAsynchronous() async throws {
        let function: @Sendable () async -> Int = {
            await Task.yield()
            return 40
        }
        #expect(
            await roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0AsynchronousThrowing() async throws {
        let function: () async throws -> Int = {
            await Task.yield()
            return 40
        }
        #expect(
            try await roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @Test
    func untypedArity0SendableAsynchronousThrowing() async throws {
        let function: @Sendable () async throws -> Int = {
            await Task.yield()
            return 40
        }
        #expect(
            try await roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity0TypedThrowing() async throws {
        let function: () throws(GeneratedBridgeMatrixError) -> Int = { 40 }
        #expect(
            try roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity0SendableTypedThrowing() async throws {
        let function: @Sendable () throws(GeneratedBridgeMatrixError) -> Int = { 40 }
        #expect(
            try roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity0AsynchronousTypedThrowing() async throws {
        let function: () async throws(GeneratedBridgeMatrixError) -> Int = {
            await Task.yield()
            return 40
        }
        #expect(
            try await roundTripGeneratedBridge(function)()
                == 40
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity0SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable () async throws(GeneratedBridgeMatrixError) -> Int = {
            await Task.yield()
            return 40
        }
        #expect(
            try await roundTripGeneratedBridge(function)()
                == 40
        )
    }
}
