// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 5 executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

@Suite
struct DynamicFunctionBridgeArity5Tests {
    @Test
    func untypedArity5Synchronous() async throws {
        let function: (Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5SendableSynchronous() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5Throwing() async throws {
        let function: (Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5SendableThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5Asynchronous() async throws {
        let function: (Int, Int, Int, Int, Int) async -> Int = {
            value0, value1, value2, value3, value4 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5SendableAsynchronous() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int) async -> Int = {
            value0, value1, value2, value3, value4 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5AsynchronousThrowing() async throws {
        let function: (Int, Int, Int, Int, Int) async throws -> Int = {
            value0, value1, value2, value3, value4 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @Test
    func untypedArity5SendableAsynchronousThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int) async throws -> Int = {
            value0, value1, value2, value3, value4 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity5TypedThrowing() async throws {
        let function: (Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity5SendableTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity5AsynchronousTypedThrowing() async throws {
        let function: (Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2, value3, value4 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity5SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2, value3, value4 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5)
                == 15
        )
    }
}
