// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 2 executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

@Suite
struct DynamicFunctionBridgeArity2Tests {
    @Test
    func untypedArity2Synchronous() async throws {
        let function: (Int, Int) -> Int = { value0, value1 in value0 + value1 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2SendableSynchronous() async throws {
        let function: @Sendable (Int, Int) -> Int = { value0, value1 in value0 + value1 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2Throwing() async throws {
        let function: (Int, Int) throws -> Int = { value0, value1 in value0 + value1 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2SendableThrowing() async throws {
        let function: @Sendable (Int, Int) throws -> Int = { value0, value1 in value0 + value1 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2Asynchronous() async throws {
        let function: (Int, Int) async -> Int = {
            value0, value1 in
            await Task.yield()
            return value0 + value1
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2SendableAsynchronous() async throws {
        let function: @Sendable (Int, Int) async -> Int = {
            value0, value1 in
            await Task.yield()
            return value0 + value1
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2AsynchronousThrowing() async throws {
        let function: (Int, Int) async throws -> Int = {
            value0, value1 in
            await Task.yield()
            return value0 + value1
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @Test
    func untypedArity2SendableAsynchronousThrowing() async throws {
        let function: @Sendable (Int, Int) async throws -> Int = {
            value0, value1 in
            await Task.yield()
            return value0 + value1
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity2TypedThrowing() async throws {
        let function: (Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1 in value0 + value1 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity2SendableTypedThrowing() async throws {
        let function: @Sendable (Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1 in value0 + value1 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity2AsynchronousTypedThrowing() async throws {
        let function: (Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1 in
            await Task.yield()
            return value0 + value1
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity2SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable (Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1 in
            await Task.yield()
            return value0 + value1
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2)
                == 3
        )
    }
}
