// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 3 executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

@Suite
struct DynamicFunctionBridgeArity3Tests {
    @Test
    func untypedArity3Synchronous() async throws {
        let function: (Int, Int, Int) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3SendableSynchronous() async throws {
        let function: @Sendable (Int, Int, Int) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3Throwing() async throws {
        let function: (Int, Int, Int) throws -> Int = { value0, value1, value2 in value0 + value1 + value2 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3SendableThrowing() async throws {
        let function: @Sendable (Int, Int, Int) throws -> Int = { value0, value1, value2 in value0 + value1 + value2 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3Asynchronous() async throws {
        let function: (Int, Int, Int) async -> Int = {
            value0, value1, value2 in
            await Task.yield()
            return value0 + value1 + value2
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3SendableAsynchronous() async throws {
        let function: @Sendable (Int, Int, Int) async -> Int = {
            value0, value1, value2 in
            await Task.yield()
            return value0 + value1 + value2
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3AsynchronousThrowing() async throws {
        let function: (Int, Int, Int) async throws -> Int = {
            value0, value1, value2 in
            await Task.yield()
            return value0 + value1 + value2
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @Test
    func untypedArity3SendableAsynchronousThrowing() async throws {
        let function: @Sendable (Int, Int, Int) async throws -> Int = {
            value0, value1, value2 in
            await Task.yield()
            return value0 + value1 + value2
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity3TypedThrowing() async throws {
        let function: (Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity3SendableTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity3AsynchronousTypedThrowing() async throws {
        let function: (Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2 in
            await Task.yield()
            return value0 + value1 + value2
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity3SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2 in
            await Task.yield()
            return value0 + value1 + value2
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3)
                == 6
        )
    }
}
