// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Every fixed arity executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

private enum GeneratedBridgeMatrixError: Error {
    case failure
}

@Suite
struct DynamicFunctionBridgeMatrixTests {
    @Test
    func untypedAritiesCoverEveryEffectAndSendability() async throws {
        try await coverUntypedBridgeArity0()
        try await coverUntypedBridgeArity1()
        try await coverUntypedBridgeArity2()
        try await coverUntypedBridgeArity3()
        try await coverUntypedBridgeArity4()
        try await coverUntypedBridgeArity5()
        try await coverUntypedBridgeArity6()
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedAritiesCoverEveryEffectAndSendability() async throws {
        try await coverTypedBridgeArity0()
        try await coverTypedBridgeArity1()
        try await coverTypedBridgeArity2()
        try await coverTypedBridgeArity3()
        try await coverTypedBridgeArity4()
        try await coverTypedBridgeArity5()
        try await coverTypedBridgeArity6()
    }
}

private func roundTripGeneratedBridge<Function>(
    _ function: Function
) -> Function {
    let source = ManagedValueBuffer(
        type: Function.self,
        minimumByteCount: 16
    )
    RuntimeResultEncoder.initializeDirectValue(
        function,
        expectedType: Function.self,
        to: source.storage
    )
    source.markInitialized()
    let boxed = FunctionReabstraction.boxDirectArgument(
        type: Function.self,
        source: source.storage
    )
    source.destroyInitializedValue()
    guard let result = boxed as? Function else {
        preconditionFailure(
            "[TestDoublesTests] Generated bridge changed the function type."
        )
    }
    return result
}

private func coverUntypedBridgeArity0() async throws {
    let synchronous: () -> Int = { 40 }
    #expect(
        roundTripGeneratedBridge(synchronous)()
            == 40
    )
    let sendableSynchronous: @Sendable () -> Int = { 40 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)()
            == 40
    )
    let throwing: () throws -> Int = { 40 }
    #expect(
        try roundTripGeneratedBridge(throwing)()
            == 40
    )
    let sendableThrowing: @Sendable () throws -> Int = { 40 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)()
            == 40
    )
    let asynchronous: () async -> Int = {
        await Task.yield()
        return 40
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)()
            == 40
    )
    let sendableAsynchronous: @Sendable () async -> Int = {
        await Task.yield()
        return 40
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)()
            == 40
    )
    let asynchronousThrowing: () async throws -> Int = {
        await Task.yield()
        return 40
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)()
            == 40
    )
    let sendableAsynchronousThrowing: @Sendable () async throws -> Int = {
        await Task.yield()
        return 40
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)()
            == 40
    )
}

private func coverUntypedBridgeArity1() async throws {
    let synchronous: (Int) -> Int = { value0 in value0 }
    #expect(
        roundTripGeneratedBridge(synchronous)(1)
            == 1
    )
    let sendableSynchronous: @Sendable (Int) -> Int = { value0 in value0 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)(1)
            == 1
    )
    let throwing: (Int) throws -> Int = { value0 in value0 }
    #expect(
        try roundTripGeneratedBridge(throwing)(1)
            == 1
    )
    let sendableThrowing: @Sendable (Int) throws -> Int = { value0 in value0 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)(1)
            == 1
    )
    let asynchronous: (Int) async -> Int = {
        value0 in
        await Task.yield()
        return value0
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)(1)
            == 1
    )
    let sendableAsynchronous: @Sendable (Int) async -> Int = {
        value0 in
        await Task.yield()
        return value0
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)(1)
            == 1
    )
    let asynchronousThrowing: (Int) async throws -> Int = {
        value0 in
        await Task.yield()
        return value0
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)(1)
            == 1
    )
    let sendableAsynchronousThrowing: @Sendable (Int) async throws -> Int = {
        value0 in
        await Task.yield()
        return value0
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)(1)
            == 1
    )
}

private func coverUntypedBridgeArity2() async throws {
    let synchronous: (Int, Int) -> Int = { value0, value1 in value0 + value1 }
    #expect(
        roundTripGeneratedBridge(synchronous)(1, 2)
            == 3
    )
    let sendableSynchronous: @Sendable (Int, Int) -> Int = { value0, value1 in value0 + value1 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)(1, 2)
            == 3
    )
    let throwing: (Int, Int) throws -> Int = { value0, value1 in value0 + value1 }
    #expect(
        try roundTripGeneratedBridge(throwing)(1, 2)
            == 3
    )
    let sendableThrowing: @Sendable (Int, Int) throws -> Int = { value0, value1 in value0 + value1 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)(1, 2)
            == 3
    )
    let asynchronous: (Int, Int) async -> Int = {
        value0, value1 in
        await Task.yield()
        return value0 + value1
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)(1, 2)
            == 3
    )
    let sendableAsynchronous: @Sendable (Int, Int) async -> Int = {
        value0, value1 in
        await Task.yield()
        return value0 + value1
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)(1, 2)
            == 3
    )
    let asynchronousThrowing: (Int, Int) async throws -> Int = {
        value0, value1 in
        await Task.yield()
        return value0 + value1
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)(1, 2)
            == 3
    )
    let sendableAsynchronousThrowing: @Sendable (Int, Int) async throws -> Int = {
        value0, value1 in
        await Task.yield()
        return value0 + value1
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)(1, 2)
            == 3
    )
}

private func coverUntypedBridgeArity3() async throws {
    let synchronous: (Int, Int, Int) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
    #expect(
        roundTripGeneratedBridge(synchronous)(1, 2, 3)
            == 6
    )
    let sendableSynchronous: @Sendable (Int, Int, Int) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)(1, 2, 3)
            == 6
    )
    let throwing: (Int, Int, Int) throws -> Int = { value0, value1, value2 in value0 + value1 + value2 }
    #expect(
        try roundTripGeneratedBridge(throwing)(1, 2, 3)
            == 6
    )
    let sendableThrowing: @Sendable (Int, Int, Int) throws -> Int = { value0, value1, value2 in value0 + value1 + value2 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)(1, 2, 3)
            == 6
    )
    let asynchronous: (Int, Int, Int) async -> Int = {
        value0, value1, value2 in
        await Task.yield()
        return value0 + value1 + value2
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)(1, 2, 3)
            == 6
    )
    let sendableAsynchronous: @Sendable (Int, Int, Int) async -> Int = {
        value0, value1, value2 in
        await Task.yield()
        return value0 + value1 + value2
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)(1, 2, 3)
            == 6
    )
    let asynchronousThrowing: (Int, Int, Int) async throws -> Int = {
        value0, value1, value2 in
        await Task.yield()
        return value0 + value1 + value2
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)(1, 2, 3)
            == 6
    )
    let sendableAsynchronousThrowing: @Sendable (Int, Int, Int) async throws -> Int = {
        value0, value1, value2 in
        await Task.yield()
        return value0 + value1 + value2
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)(1, 2, 3)
            == 6
    )
}

private func coverUntypedBridgeArity4() async throws {
    let synchronous: (Int, Int, Int, Int) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
    #expect(
        roundTripGeneratedBridge(synchronous)(1, 2, 3, 4)
            == 10
    )
    let sendableSynchronous: @Sendable (Int, Int, Int, Int) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)(1, 2, 3, 4)
            == 10
    )
    let throwing: (Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
    #expect(
        try roundTripGeneratedBridge(throwing)(1, 2, 3, 4)
            == 10
    )
    let sendableThrowing: @Sendable (Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)(1, 2, 3, 4)
            == 10
    )
    let asynchronous: (Int, Int, Int, Int) async -> Int = {
        value0, value1, value2, value3 in
        await Task.yield()
        return value0 + value1 + value2 + value3
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)(1, 2, 3, 4)
            == 10
    )
    let sendableAsynchronous: @Sendable (Int, Int, Int, Int) async -> Int = {
        value0, value1, value2, value3 in
        await Task.yield()
        return value0 + value1 + value2 + value3
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)(1, 2, 3, 4)
            == 10
    )
    let asynchronousThrowing: (Int, Int, Int, Int) async throws -> Int = {
        value0, value1, value2, value3 in
        await Task.yield()
        return value0 + value1 + value2 + value3
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)(1, 2, 3, 4)
            == 10
    )
    let sendableAsynchronousThrowing: @Sendable (Int, Int, Int, Int) async throws -> Int = {
        value0, value1, value2, value3 in
        await Task.yield()
        return value0 + value1 + value2 + value3
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)(1, 2, 3, 4)
            == 10
    )
}

private func coverUntypedBridgeArity5() async throws {
    let synchronous: (Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
    #expect(
        roundTripGeneratedBridge(synchronous)(1, 2, 3, 4, 5)
            == 15
    )
    let sendableSynchronous: @Sendable (Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)(1, 2, 3, 4, 5)
            == 15
    )
    let throwing: (Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
    #expect(
        try roundTripGeneratedBridge(throwing)(1, 2, 3, 4, 5)
            == 15
    )
    let sendableThrowing: @Sendable (Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)(1, 2, 3, 4, 5)
            == 15
    )
    let asynchronous: (Int, Int, Int, Int, Int) async -> Int = {
        value0, value1, value2, value3, value4 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)(1, 2, 3, 4, 5)
            == 15
    )
    let sendableAsynchronous: @Sendable (Int, Int, Int, Int, Int) async -> Int = {
        value0, value1, value2, value3, value4 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)(1, 2, 3, 4, 5)
            == 15
    )
    let asynchronousThrowing: (Int, Int, Int, Int, Int) async throws -> Int = {
        value0, value1, value2, value3, value4 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)(1, 2, 3, 4, 5)
            == 15
    )
    let sendableAsynchronousThrowing: @Sendable (Int, Int, Int, Int, Int) async throws -> Int = {
        value0, value1, value2, value3, value4 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)(1, 2, 3, 4, 5)
            == 15
    )
}

private func coverUntypedBridgeArity6() async throws {
    let synchronous: (Int, Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
    #expect(
        roundTripGeneratedBridge(synchronous)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let sendableSynchronous: @Sendable (Int, Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
    #expect(
        roundTripGeneratedBridge(sendableSynchronous)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let throwing: (Int, Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
    #expect(
        try roundTripGeneratedBridge(throwing)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let sendableThrowing: @Sendable (Int, Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
    #expect(
        try roundTripGeneratedBridge(sendableThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let asynchronous: (Int, Int, Int, Int, Int, Int) async -> Int = {
        value0, value1, value2, value3, value4, value5 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4 + value5
    }
    #expect(
        await roundTripGeneratedBridge(asynchronous)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let sendableAsynchronous: @Sendable (Int, Int, Int, Int, Int, Int) async -> Int = {
        value0, value1, value2, value3, value4, value5 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4 + value5
    }
    #expect(
        await roundTripGeneratedBridge(sendableAsynchronous)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let asynchronousThrowing: (Int, Int, Int, Int, Int, Int) async throws -> Int = {
        value0, value1, value2, value3, value4, value5 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4 + value5
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let sendableAsynchronousThrowing: @Sendable (Int, Int, Int, Int, Int, Int) async throws -> Int = {
        value0, value1, value2, value3, value4, value5 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4 + value5
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity0() async throws {
    let typedThrowing: () throws(GeneratedBridgeMatrixError) -> Int = { 40 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)()
            == 40
    )
    let sendableTypedThrowing: @Sendable () throws(GeneratedBridgeMatrixError) -> Int = { 40 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)()
            == 40
    )
    let asynchronousTypedThrowing: () async throws(GeneratedBridgeMatrixError) -> Int = {
        await Task.yield()
        return 40
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)()
            == 40
    )
    let sendableAsynchronousTypedThrowing: @Sendable () async throws(GeneratedBridgeMatrixError) -> Int = {
        await Task.yield()
        return 40
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)()
            == 40
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity1() async throws {
    let typedThrowing: (Int) throws(GeneratedBridgeMatrixError) -> Int = { value0 in value0 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)(1)
            == 1
    )
    let sendableTypedThrowing: @Sendable (Int) throws(GeneratedBridgeMatrixError) -> Int = { value0 in value0 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)(1)
            == 1
    )
    let asynchronousTypedThrowing: (Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0 in
        await Task.yield()
        return value0
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)(1)
            == 1
    )
    let sendableAsynchronousTypedThrowing: @Sendable (Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0 in
        await Task.yield()
        return value0
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)(1)
            == 1
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity2() async throws {
    let typedThrowing: (Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1 in value0 + value1 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)(1, 2)
            == 3
    )
    let sendableTypedThrowing: @Sendable (Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1 in value0 + value1 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)(1, 2)
            == 3
    )
    let asynchronousTypedThrowing: (Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1 in
        await Task.yield()
        return value0 + value1
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)(1, 2)
            == 3
    )
    let sendableAsynchronousTypedThrowing: @Sendable (Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1 in
        await Task.yield()
        return value0 + value1
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)(1, 2)
            == 3
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity3() async throws {
    let typedThrowing: (Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)(1, 2, 3)
            == 6
    )
    let sendableTypedThrowing: @Sendable (Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2 in value0 + value1 + value2 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)(1, 2, 3)
            == 6
    )
    let asynchronousTypedThrowing: (Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2 in
        await Task.yield()
        return value0 + value1 + value2
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)(1, 2, 3)
            == 6
    )
    let sendableAsynchronousTypedThrowing: @Sendable (Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2 in
        await Task.yield()
        return value0 + value1 + value2
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)(1, 2, 3)
            == 6
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity4() async throws {
    let typedThrowing: (Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)(1, 2, 3, 4)
            == 10
    )
    let sendableTypedThrowing: @Sendable (Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)(1, 2, 3, 4)
            == 10
    )
    let asynchronousTypedThrowing: (Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2, value3 in
        await Task.yield()
        return value0 + value1 + value2 + value3
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)(1, 2, 3, 4)
            == 10
    )
    let sendableAsynchronousTypedThrowing: @Sendable (Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2, value3 in
        await Task.yield()
        return value0 + value1 + value2 + value3
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)(1, 2, 3, 4)
            == 10
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity5() async throws {
    let typedThrowing: (Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)(1, 2, 3, 4, 5)
            == 15
    )
    let sendableTypedThrowing: @Sendable (Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4 in value0 + value1 + value2 + value3 + value4 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)(1, 2, 3, 4, 5)
            == 15
    )
    let asynchronousTypedThrowing: (Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2, value3, value4 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)(1, 2, 3, 4, 5)
            == 15
    )
    let sendableAsynchronousTypedThrowing: @Sendable (Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2, value3, value4 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)(1, 2, 3, 4, 5)
            == 15
    )
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func coverTypedBridgeArity6() async throws {
    let typedThrowing: (Int, Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
    #expect(
        try roundTripGeneratedBridge(typedThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let sendableTypedThrowing: @Sendable (Int, Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
    #expect(
        try roundTripGeneratedBridge(sendableTypedThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let asynchronousTypedThrowing: (Int, Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2, value3, value4, value5 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4 + value5
    }
    #expect(
        try await roundTripGeneratedBridge(asynchronousTypedThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
    let sendableAsynchronousTypedThrowing: @Sendable (Int, Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
        value0, value1, value2, value3, value4, value5 in
        await Task.yield()
        return value0 + value1 + value2 + value3 + value4 + value5
    }
    #expect(
        try await roundTripGeneratedBridge(sendableAsynchronousTypedThrowing)(1, 2, 3, 4, 5, 6)
            == 21
    )
}
