// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 6 executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

@Suite
struct DynamicFunctionBridgeArity6Tests {
    @Test
    func untypedArity6Synchronous() async throws {
        let function: (Int, Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6SendableSynchronous() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int, Int) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6Throwing() async throws {
        let function: (Int, Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6SendableThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6Asynchronous() async throws {
        let function: (Int, Int, Int, Int, Int, Int) async -> Int = {
            value0, value1, value2, value3, value4, value5 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4 + value5
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6SendableAsynchronous() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int, Int) async -> Int = {
            value0, value1, value2, value3, value4, value5 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4 + value5
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6AsynchronousThrowing() async throws {
        let function: (Int, Int, Int, Int, Int, Int) async throws -> Int = {
            value0, value1, value2, value3, value4, value5 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4 + value5
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @Test
    func untypedArity6SendableAsynchronousThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int, Int) async throws -> Int = {
            value0, value1, value2, value3, value4, value5 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4 + value5
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity6TypedThrowing() async throws {
        let function: (Int, Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity6SendableTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3, value4, value5 in value0 + value1 + value2 + value3 + value4 + value5 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                == 21
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity6AsynchronousTypedThrowing() async throws {
        let function: (Int, Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2, value3, value4, value5 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4 + value5
        }
        #if arch(x86_64)
            let functionType = type(of: function)
            #expect(
                FunctionReabstraction.automaticResultUnsupportedReason(
                    for: functionType
                )?.contains("x86_64 async typed-error return bridge") == true
            )
        #else
            #expect(
                try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                    == 21
            )
        #endif
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity6SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2, value3, value4, value5 in
            await Task.yield()
            return value0 + value1 + value2 + value3 + value4 + value5
        }
        #if arch(x86_64)
            let functionType = type(of: function)
            #expect(
                FunctionReabstraction.automaticResultUnsupportedReason(
                    for: functionType
                )?.contains("x86_64 async typed-error return bridge") == true
            )
        #else
            #expect(
                try await roundTripGeneratedBridge(function)(1, 2, 3, 4, 5, 6)
                    == 21
            )
        #endif
    }
}
