// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Arity 4 executes every supported effect and sendability branch.

import Testing

@testable import TestDoubles

@Suite
struct DynamicFunctionBridgeArity4Tests {
    @Test
    func untypedArity4Synchronous() async throws {
        let function: (Int, Int, Int, Int) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4SendableSynchronous() async throws {
        let function: @Sendable (Int, Int, Int, Int) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
        #expect(
            roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4Throwing() async throws {
        let function: (Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4SendableThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int) throws -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4Asynchronous() async throws {
        let function: (Int, Int, Int, Int) async -> Int = {
            value0, value1, value2, value3 in
            await Task.yield()
            return value0 + value1 + value2 + value3
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4SendableAsynchronous() async throws {
        let function: @Sendable (Int, Int, Int, Int) async -> Int = {
            value0, value1, value2, value3 in
            await Task.yield()
            return value0 + value1 + value2 + value3
        }
        #expect(
            await roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4AsynchronousThrowing() async throws {
        let function: (Int, Int, Int, Int) async throws -> Int = {
            value0, value1, value2, value3 in
            await Task.yield()
            return value0 + value1 + value2 + value3
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @Test
    func untypedArity4SendableAsynchronousThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int) async throws -> Int = {
            value0, value1, value2, value3 in
            await Task.yield()
            return value0 + value1 + value2 + value3
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity4TypedThrowing() async throws {
        let function: (Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity4SendableTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int) throws(GeneratedBridgeMatrixError) -> Int = { value0, value1, value2, value3 in value0 + value1 + value2 + value3 }
        #expect(
            try roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity4AsynchronousTypedThrowing() async throws {
        let function: (Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2, value3 in
            await Task.yield()
            return value0 + value1 + value2 + value3
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }

    @available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
    @Test
    func typedArity4SendableAsynchronousTypedThrowing() async throws {
        let function: @Sendable (Int, Int, Int, Int) async throws(GeneratedBridgeMatrixError) -> Int = {
            value0, value1, value2, value3 in
            await Task.yield()
            return value0 + value1 + value2 + value3
        }
        #expect(
            try await roundTripGeneratedBridge(function)(1, 2, 3, 4)
                == 10
        )
    }
}
