// Generated by ManualStubGeneratorTool; do not edit by hand.

import Foundation
import TestDoubles

struct GeneratedManualStubServiceStubConformer: GeneratedManualStubService, AutomaticStubConformer {
    typealias StubbedProtocol = any GeneratedManualStubService

    static let compilerEvidence: StubCompilerEvidence<StubbedProtocol> = StubCompilerEvidence(
        runtimeConstruction: .requirements([
            .method(Int.self, returning: String.self),
            .method(String.self, returning: String.self),
            .method(Int.self, returning: Void.self, throwing: GeneratedManualStubFailure.self),
            .method(Int.self, returning: String.self, throwing: GeneratedManualStubFailure.self, isAsync: true),
            .getter(Int.self),
            .setter(Int.self),
            .subscriptGetter(indexedBy: Int.self, returning: String.self),
            .subscriptSetter(indexedBy: Int.self, assigning: String.self)
        ]),
        compiledFallbackEligibility: .generatedConformer,
        sourceSupport: StubSourceSupportReport(
            protocolName: "GeneratedManualStubService",
            requirements: [
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "render(_:)",
                    kind: .method,
                    declarationIndex: 0,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "render(_:)",
                    kind: .method,
                    declarationIndex: 1,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "save(_:)",
                    kind: .method,
                    declarationIndex: 2,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "refresh(_:)",
                    kind: .method,
                    declarationIndex: 3,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "count",
                    kind: .getter,
                    declarationIndex: 4,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "count",
                    kind: .setter,
                    declarationIndex: 5,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "subscript",
                    kind: .getter,
                    declarationIndex: 6,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubService",
                    name: "subscript",
                    kind: .setter,
                    declarationIndex: 7,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                )
            ]
        )
    )

    let stub: CompiledStub<Self>

    static func eraseToStubbedProtocol(_ conformer: GeneratedManualStubServiceStubConformer) -> StubbedProtocol { conformer }

    func render(_ value: Int) -> String { stub.call(value) }

    func render(_ value: String) -> String { stub.call(value) }

    func save(_ value: Int) throws(GeneratedManualStubFailure) { try stub.throwingCall(value, throwing: GeneratedManualStubFailure.self) }

    func refresh(_ value: Int) async throws(GeneratedManualStubFailure) -> String { try await stub.throwingCall(value, throwing: GeneratedManualStubFailure.self) }

    var count: Int {
        get { stub.call() }
        set { stub.call(newValue) }
    }

    subscript(_ value: Int) -> String {
        get { stub.call(value) }
        set { stub.call(value, newValue) }
    }
}

typealias GeneratedManualStubServiceStub = CompiledStub<GeneratedManualStubServiceStubConformer>

struct GeneratedManualStubCounterStubConformer: GeneratedManualStubCounter, AutomaticStubConformer {
    typealias StubbedProtocol = any GeneratedManualStubCounter

    static let compilerEvidence: StubCompilerEvidence<StubbedProtocol> = StubCompilerEvidence(
        runtimeConstruction: .requirements([
            .method(Int.self, returning: Void.self),
            .getter(Int.self)
        ]),
        compiledFallbackEligibility: .generatedConformer,
        sourceSupport: StubSourceSupportReport(
            protocolName: "GeneratedManualStubCounter",
            requirements: [
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubCounter",
                    name: "increment(by:)",
                    kind: .method,
                    declarationIndex: 0,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                ),
                StubRequirementSupport(
                    declaringProtocol: "GeneratedManualStubCounter",
                    name: "value",
                    kind: .getter,
                    declarationIndex: 1,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                )
            ]
        )
    )

    let stub: CompiledStub<Self>

    static func eraseToStubbedProtocol(_ conformer: GeneratedManualStubCounterStubConformer) -> StubbedProtocol { conformer }

    func increment(by amount: Int) { stub.call(amount) }

    var value: Int { stub.call() }
}

typealias GeneratedManualStubCounterStub = CompiledStub<GeneratedManualStubCounterStubConformer>

struct GeneratedOpaqueResultServiceStubConformer: GeneratedOpaqueResultService, AutomaticStubConformer {
    typealias StubbedProtocol = any GeneratedOpaqueResultService

    static let compilerEvidence: StubCompilerEvidence<StubbedProtocol> = StubCompilerEvidence(
        runtimeConstruction: .requirements([
            .method(returning: Data.self)
        ]),
        compiledFallbackEligibility: .generatedConformer,
        sourceSupport: StubSourceSupportReport(
            protocolName: "GeneratedOpaqueResultService",
            requirements: [
                StubRequirementSupport(
                    declaringProtocol: "GeneratedOpaqueResultService",
                    name: "load()",
                    kind: .method,
                    declarationIndex: 0,
                    runtimeEligibility: .compilerDescribed,
                    compiledEligibility: .generatedConformer
                )
            ]
        )
    )

    let stub: CompiledStub<Self>

    static func eraseToStubbedProtocol(_ conformer: GeneratedOpaqueResultServiceStubConformer) -> StubbedProtocol { conformer }

    func load() -> Data { stub.call() }
}

typealias GeneratedOpaqueResultServiceStub = CompiledStub<GeneratedOpaqueResultServiceStubConformer>

actor GeneratedActorServiceStubConformer: GeneratedActorService, AutomaticStubConformer {
    typealias StubbedProtocol = any GeneratedActorService

    static let compilerEvidence: StubCompilerEvidence<StubbedProtocol> = StubCompilerEvidence(
        runtimeConstruction: .unavailable(reason: "Actor protocols require a genuine actor instance."),
        compiledFallbackEligibility: .generatedConformer,
        sourceSupport: StubSourceSupportReport(
            protocolName: "GeneratedActorService",
            requirements: [
                StubRequirementSupport(
                    declaringProtocol: "GeneratedActorService",
                    name: "load(_:)",
                    kind: .method,
                    declarationIndex: 0,
                    runtimeEligibility: .unavailable(reason: "Actor protocols require a genuine actor instance."),
                    compiledEligibility: .generatedConformer
                )
            ]
        )
    )

    let stub: CompiledStub<GeneratedActorServiceStubConformer>

    init(stub: CompiledStub<GeneratedActorServiceStubConformer>) { self.stub = stub }

    static func eraseToStubbedProtocol(_ conformer: GeneratedActorServiceStubConformer) -> StubbedProtocol { conformer }

    func load(_ identifier: Int) -> String { stub.call(identifier) }
}

typealias GeneratedActorServiceStub = CompiledStub<GeneratedActorServiceStubConformer>
