// Generated by ManualStubGeneratorTool; do not edit by hand.

import Foundation
import TestDoubles

struct GeneratedManualStubServiceStubConformer: GeneratedManualStubService, ManualStubConformer {
    let stub: ManualStub<Self>

    func render(_ value: Int) -> String { stub.call(value) }

    func render(_ value: String) -> String { stub.call(value) }

    func save(_ value: Int) throws(GeneratedManualStubFailure) { try stub.throwingCall(value, throwing: GeneratedManualStubFailure.self) }

    func refresh(_ value: Int) async throws(GeneratedManualStubFailure) -> String { try await stub.throwingCall(value, throwing: GeneratedManualStubFailure.self) }

    var count: Int {
        get { stub.call() }
        set { stub.call(newValue) }
    }

    subscript(_ value: Int) -> String {
        get { stub.call(value) }
        set { stub.call(value, newValue) }
    }
}

typealias GeneratedManualStubServiceStub = ManualStub<GeneratedManualStubServiceStubConformer>

extension ManualStub where T == GeneratedManualStubServiceStubConformer {
    /// Tries runtime synthesis, then uses this compiled conformer when needed.
    static func automatic() -> Stub<any GeneratedManualStubService> {
        Stub(fallingBackTo: GeneratedManualStubServiceStubConformer.self, erasingWith: { $0 })
    }
}

struct GeneratedManualStubCounterStubConformer: GeneratedManualStubCounter, ManualStubConformer {
    let stub: ManualStub<Self>

    func increment(by amount: Int) { stub.call(amount) }

    var value: Int { stub.call() }
}

typealias GeneratedManualStubCounterStub = ManualStub<GeneratedManualStubCounterStubConformer>

extension ManualStub where T == GeneratedManualStubCounterStubConformer {
    /// Tries runtime synthesis, then uses this compiled conformer when needed.
    static func automatic() -> Stub<any GeneratedManualStubCounter> {
        Stub(fallingBackTo: GeneratedManualStubCounterStubConformer.self, erasingWith: { $0 })
    }
}

struct GeneratedOpaqueResultServiceStubConformer: GeneratedOpaqueResultService, ManualStubConformer {
    let stub: ManualStub<Self>

    func load() -> Data { stub.call() }
}

typealias GeneratedOpaqueResultServiceStub = ManualStub<GeneratedOpaqueResultServiceStubConformer>

extension ManualStub where T == GeneratedOpaqueResultServiceStubConformer {
    /// Tries runtime synthesis, then uses this compiled conformer when needed.
    static func automatic() -> Stub<any GeneratedOpaqueResultService> {
        Stub(fallingBackTo: GeneratedOpaqueResultServiceStubConformer.self, erasingWith: { $0 })
    }
}

actor GeneratedActorServiceStubConformer: GeneratedActorService, ManualStubConformer {
    let stub: ManualStub<GeneratedActorServiceStubConformer>

    init(stub: ManualStub<GeneratedActorServiceStubConformer>) { self.stub = stub }

    func load(_ identifier: Int) -> String { stub.call(identifier) }
}

typealias GeneratedActorServiceStub = ManualStub<GeneratedActorServiceStubConformer>

extension ManualStub where T == GeneratedActorServiceStubConformer {
    /// Tries runtime synthesis, then uses this compiled conformer when needed.
    static func automatic() -> Stub<any GeneratedActorService> {
        Stub(fallingBackTo: GeneratedActorServiceStubConformer.self, erasingWith: { $0 })
    }
}
