// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Fixed concrete arities are required because Swift cannot reliably erase a
// variadic function type to Any.
// swiftlint:disable file_length

import Echo

func dynamicallyBoxFunctionArgument(
    function: UnsafeRawPointer,
    context: UnsafeRawPointer?,
    metadata: FunctionMetadata,
    discriminator: UInt16
) -> Any {
    // Opening six independently discovered parameter types requires one local
    // generic function per level. The nesting mirrors Swift's existential-open
    // operation and is bounded by the documented arity limit.
    // swiftlint:disable nesting
    let plan = FunctionBridgePlan(metadata)
    let invocation = DynamicFunctionInvocation(
        function: function,
        context: context,
        discriminator: discriminator,
        plan: plan
    )
    let isSendable = metadata.flags.bits & 0x4000_0000 != 0
    let isThrowing = plan.isThrowing
    let isAsync = plan.isAsync

    func boxResult<Result>(_ resultType: Result.Type) -> Any {
        switch invocation.parameterTypes.count {
            case 0:
                return boxDynamicFunction0(
                    invocation,
                    resultType: resultType,
                    isSendable: isSendable,
                    isThrowing: isThrowing,
                    isAsync: isAsync
                )
            case 1:
                func openParameter0<P0>(_ type0: P0.Type) -> Any {
                    return boxDynamicFunction1(
                        invocation,
                        resultType: resultType,
                        isSendable: isSendable,
                        isThrowing: isThrowing,
                        isAsync: isAsync,
                        type0
                    )
                }
                return _openExistential(
                    invocation.parameterTypes[0],
                    do: openParameter0
                )
            case 2:
                func openParameter0<P0>(_ type0: P0.Type) -> Any {
                    func openParameter1<P1>(_ type1: P1.Type) -> Any {
                        return boxDynamicFunction2(
                            invocation,
                            resultType: resultType,
                            isSendable: isSendable,
                            isThrowing: isThrowing,
                            isAsync: isAsync,
                            type0, type1
                        )
                    }
                    return _openExistential(
                        invocation.parameterTypes[1],
                        do: openParameter1
                    )
                }
                return _openExistential(
                    invocation.parameterTypes[0],
                    do: openParameter0
                )
            case 3:
                func openParameter0<P0>(_ type0: P0.Type) -> Any {
                    func openParameter1<P1>(_ type1: P1.Type) -> Any {
                        func openParameter2<P2>(_ type2: P2.Type) -> Any {
                            return boxDynamicFunction3(
                                invocation,
                                resultType: resultType,
                                isSendable: isSendable,
                                isThrowing: isThrowing,
                                isAsync: isAsync,
                                type0, type1, type2
                            )
                        }
                        return _openExistential(
                            invocation.parameterTypes[2],
                            do: openParameter2
                        )
                    }
                    return _openExistential(
                        invocation.parameterTypes[1],
                        do: openParameter1
                    )
                }
                return _openExistential(
                    invocation.parameterTypes[0],
                    do: openParameter0
                )
            case 4:
                func openParameter0<P0>(_ type0: P0.Type) -> Any {
                    func openParameter1<P1>(_ type1: P1.Type) -> Any {
                        func openParameter2<P2>(_ type2: P2.Type) -> Any {
                            func openParameter3<P3>(_ type3: P3.Type) -> Any {
                                return boxDynamicFunction4(
                                    invocation,
                                    resultType: resultType,
                                    isSendable: isSendable,
                                    isThrowing: isThrowing,
                                    isAsync: isAsync,
                                    type0, type1, type2, type3
                                )
                            }
                            return _openExistential(
                                invocation.parameterTypes[3],
                                do: openParameter3
                            )
                        }
                        return _openExistential(
                            invocation.parameterTypes[2],
                            do: openParameter2
                        )
                    }
                    return _openExistential(
                        invocation.parameterTypes[1],
                        do: openParameter1
                    )
                }
                return _openExistential(
                    invocation.parameterTypes[0],
                    do: openParameter0
                )
            case 5:
                func openParameter0<P0>(_ type0: P0.Type) -> Any {
                    func openParameter1<P1>(_ type1: P1.Type) -> Any {
                        func openParameter2<P2>(_ type2: P2.Type) -> Any {
                            func openParameter3<P3>(_ type3: P3.Type) -> Any {
                                func openParameter4<P4>(_ type4: P4.Type) -> Any {
                                    return boxDynamicFunction5(
                                        invocation,
                                        resultType: resultType,
                                        isSendable: isSendable,
                                        isThrowing: isThrowing,
                                        isAsync: isAsync,
                                        type0, type1, type2, type3, type4
                                    )
                                }
                                return _openExistential(
                                    invocation.parameterTypes[4],
                                    do: openParameter4
                                )
                            }
                            return _openExistential(
                                invocation.parameterTypes[3],
                                do: openParameter3
                            )
                        }
                        return _openExistential(
                            invocation.parameterTypes[2],
                            do: openParameter2
                        )
                    }
                    return _openExistential(
                        invocation.parameterTypes[1],
                        do: openParameter1
                    )
                }
                return _openExistential(
                    invocation.parameterTypes[0],
                    do: openParameter0
                )
            case 6:
                func openParameter0<P0>(_ type0: P0.Type) -> Any {
                    func openParameter1<P1>(_ type1: P1.Type) -> Any {
                        func openParameter2<P2>(_ type2: P2.Type) -> Any {
                            func openParameter3<P3>(_ type3: P3.Type) -> Any {
                                func openParameter4<P4>(_ type4: P4.Type) -> Any {
                                    func openParameter5<P5>(_ type5: P5.Type) -> Any {
                                        return boxDynamicFunction6(
                                            invocation,
                                            resultType: resultType,
                                            isSendable: isSendable,
                                            isThrowing: isThrowing,
                                            isAsync: isAsync,
                                            type0, type1, type2, type3, type4, type5
                                        )
                                    }
                                    return _openExistential(
                                        invocation.parameterTypes[5],
                                        do: openParameter5
                                    )
                                }
                                return _openExistential(
                                    invocation.parameterTypes[4],
                                    do: openParameter4
                                )
                            }
                            return _openExistential(
                                invocation.parameterTypes[3],
                                do: openParameter3
                            )
                        }
                        return _openExistential(
                            invocation.parameterTypes[2],
                            do: openParameter2
                        )
                    }
                    return _openExistential(
                        invocation.parameterTypes[1],
                        do: openParameter1
                    )
                }
                return _openExistential(
                    invocation.parameterTypes[0],
                    do: openParameter0
                )
            default:
                preconditionFailure(
                    "[TestDoubles] Dynamic function arity changed after validation."
                )
        }
    }
    return _openExistential(metadata.resultType, do: boxResult)
    // swiftlint:enable nesting
}

private func boxDynamicFunction0<Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction0(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable () async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: () async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable () async -> Result = {
            await invocation.callAsync(
                [],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: () async -> Result = {
            await invocation.callAsync(
                [],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable () throws -> Result = {
            try invocation.callThrowing(
                [],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: () throws -> Result = {
            try invocation.callThrowing(
                [],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable () -> Result = {
            invocation.call(
                [],
                returning: resultType
            )
        }
        return closure
    }
    let closure: () -> Result = {
        invocation.call(
            [],
            returning: resultType
        )
    }
    return closure
}

private func boxDynamicFunction1<P0, Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool,
    _: P0.Type
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction1(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync,
                P0.self
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable (P0) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: (P0) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable (P0) async -> Result = {
            await invocation.callAsync(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0) async -> Result = {
            await invocation.callAsync(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable (P0) throws -> Result = {
            try invocation.callThrowing(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: (P0) throws -> Result = {
            try invocation.callThrowing(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0) -> Result = {
            invocation.call(
                [$0],
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0) -> Result = {
        invocation.call(
            [$0],
            returning: resultType
        )
    }
    return closure
}

private func boxDynamicFunction2<P0, P1, Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction2(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync,
                P0.self,
                P1.self
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable (P0, P1) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: (P0, P1) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1) async -> Result = {
            await invocation.callAsync(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1) async -> Result = {
            await invocation.callAsync(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable (P0, P1) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: (P0, P1) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1) -> Result = {
            invocation.call(
                [$0, $1],
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1) -> Result = {
        invocation.call(
            [$0, $1],
            returning: resultType
        )
    }
    return closure
}

private func boxDynamicFunction3<P0, P1, P2, Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction3(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync,
                P0.self,
                P1.self,
                P2.self
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: (P0, P1, P2) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: (P0, P1, P2) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2) -> Result = {
            invocation.call(
                [$0, $1, $2],
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2) -> Result = {
        invocation.call(
            [$0, $1, $2],
            returning: resultType
        )
    }
    return closure
}

private func boxDynamicFunction4<P0, P1, P2, P3, Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type,
    _: P3.Type
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction4(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync,
                P0.self,
                P1.self,
                P2.self,
                P3.self
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2, P3) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: (P0, P1, P2, P3) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2, P3) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2, P3) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2, P3) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: (P0, P1, P2, P3) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2, P3) -> Result = {
            invocation.call(
                [$0, $1, $2, $3],
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2, P3) -> Result = {
        invocation.call(
            [$0, $1, $2, $3],
            returning: resultType
        )
    }
    return closure
}

private func boxDynamicFunction5<P0, P1, P2, P3, P4, Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type,
    _: P3.Type,
    _: P4.Type
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction5(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync,
                P0.self,
                P1.self,
                P2.self,
                P3.self,
                P4.self
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: (P0, P1, P2, P3, P4) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2, P3, P4) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: (P0, P1, P2, P3, P4) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4) -> Result = {
            invocation.call(
                [$0, $1, $2, $3, $4],
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2, P3, P4) -> Result = {
        invocation.call(
            [$0, $1, $2, $3, $4],
            returning: resultType
        )
    }
    return closure
}

private func boxDynamicFunction6<P0, P1, P2, P3, P4, P5, Result>(
    _ invocation: DynamicFunctionInvocation,
    resultType: Result.Type,
    isSendable: Bool,
    isThrowing: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type,
    _: P3.Type,
    _: P4.Type,
    _: P5.Type
) -> Any {
    if let errorType = invocation.typedErrorType {
        guard #available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *) else {
            preconditionFailure(
                "[TestDoubles] Typed closure runtime support is unavailable on this OS version."
            )
        }
        func openFailure<Failure: Error>(_ failureType: Failure.Type) -> Any {
            boxDynamicTypedFunction6(
                invocation,
                failureType: failureType,
                resultType: resultType,
                isSendable: isSendable,
                isAsync: isAsync,
                P0.self,
                P1.self,
                P2.self,
                P3.self,
                P4.self,
                P5.self
            )
        }
        return _openExistential(errorType, do: openFailure)
    }
    if isAsync, isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4, P5) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isThrowing {
        let closure: (P0, P1, P2, P3, P4, P5) async throws -> Result = {
            try await invocation.callAsyncThrowing(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4, P5) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2, P3, P4, P5) async -> Result = {
            await invocation.callAsync(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4, P5) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    if isThrowing {
        let closure: (P0, P1, P2, P3, P4, P5) throws -> Result = {
            try invocation.callThrowing(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4, P5) -> Result = {
            invocation.call(
                [$0, $1, $2, $3, $4, $5],
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2, P3, P4, P5) -> Result = {
        invocation.call(
            [$0, $1, $2, $3, $4, $5],
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction0<Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable () async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: () async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable () throws(Failure) -> Result = {
            try invocation.callTyped(
                [],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: () throws(Failure) -> Result = {
        try invocation.callTyped(
            [],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction1<P0, Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool,
    _: P0.Type
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable (P0) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0) throws(Failure) -> Result = {
            try invocation.callTyped(
                [$0],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0) throws(Failure) -> Result = {
        try invocation.callTyped(
            [$0],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction2<P0, P1, Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1) throws(Failure) -> Result = {
            try invocation.callTyped(
                [$0, $1],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1) throws(Failure) -> Result = {
        try invocation.callTyped(
            [$0, $1],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction3<P0, P1, P2, Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2) throws(Failure) -> Result = {
            try invocation.callTyped(
                [$0, $1, $2],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2) throws(Failure) -> Result = {
        try invocation.callTyped(
            [$0, $1, $2],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction4<P0, P1, P2, P3, Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type,
    _: P3.Type
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2, P3) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2, $3],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2, P3) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2, $3],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2, P3) throws(Failure) -> Result = {
            try invocation.callTyped(
                [$0, $1, $2, $3],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2, P3) throws(Failure) -> Result = {
        try invocation.callTyped(
            [$0, $1, $2, $3],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction5<P0, P1, P2, P3, P4, Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type,
    _: P3.Type,
    _: P4.Type
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2, $3, $4],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2, P3, P4) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2, $3, $4],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4) throws(Failure) -> Result = {
            try invocation.callTyped(
                [$0, $1, $2, $3, $4],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2, P3, P4) throws(Failure) -> Result = {
        try invocation.callTyped(
            [$0, $1, $2, $3, $4],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

@available(macOS 15, iOS 18, macCatalyst 18, tvOS 18, visionOS 2, watchOS 11, *)
private func boxDynamicTypedFunction6<P0, P1, P2, P3, P4, P5, Failure: Error, Result>(
    _ invocation: DynamicFunctionInvocation,
    failureType: Failure.Type,
    resultType: Result.Type,
    isSendable: Bool,
    isAsync: Bool,
    _: P0.Type,
    _: P1.Type,
    _: P2.Type,
    _: P3.Type,
    _: P4.Type,
    _: P5.Type
) -> Any {
    if isAsync, isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4, P5) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2, $3, $4, $5],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isAsync {
        let closure: (P0, P1, P2, P3, P4, P5) async throws(Failure) -> Result = {
            try await invocation.callAsyncTyped(
                [$0, $1, $2, $3, $4, $5],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    if isSendable {
        let closure: @Sendable (P0, P1, P2, P3, P4, P5) throws(Failure) -> Result = {
            try invocation.callTyped(
                [$0, $1, $2, $3, $4, $5],
                throwing: failureType,
                returning: resultType
            )
        }
        return closure
    }
    let closure: (P0, P1, P2, P3, P4, P5) throws(Failure) -> Result = {
        try invocation.callTyped(
            [$0, $1, $2, $3, $4, $5],
            throwing: failureType,
            returning: resultType
        )
    }
    return closure
}

// swiftlint:enable file_length
