// Auto-generated by Scripts/generate_thunks.swift — DO NOT EDIT
//
// ABI-class thunks for witness table patching.
// W1 = 8-byte (Int, Bool, Double, Array, class refs, custom structs)
// W2 = 16-byte (String)
// V  = Void
//
// Thunks: 336 total across 0-3 arg arities.

/// Describes a method signature for thunk lookup.
public struct MethodSignature: Hashable, Sendable {
    public let args: [String]
    public let ret: String

    public init(args: [String], ret: String) {
        self.args = args
        self.ret = ret
    }

    public static func getter(_ type: String) -> MethodSignature { .init(args: [], ret: type) }
    public static func method(_ args: [String], returning ret: String) -> MethodSignature { .init(args: args, ret: ret) }

    /// Maps this signature to its ABI-class equivalent for thunk lookup.
    var abiSignature: MethodSignature {
        MethodSignature(args: args.map(argABI), ret: retABI(ret))
    }
}
private func argABI(_ typeName: String) -> String {
    switch typeName {
    case "W1", "W2": return typeName  // already ABI class (from Slot.from())
    case "String": return "W2"
    default: return "W1"
    }
}

private func retABI(_ typeName: String) -> String {
    switch typeName {
    case "W1", "W2", "V": return typeName  // already ABI class
    case "Void": return "V"
    case "String": return "W2"
    default: return "W1"
    }
}

/// Determines if a return type needs ARC retain when returned as raw bits.
func isReferenceReturn(_ typeName: String) -> Bool {
    switch typeName {
    case "Int", "Bool", "Double", "Float", "String", "Void",
         "UInt", "Int8", "Int16", "Int32", "Int64",
         "UInt8", "UInt16", "UInt32", "UInt64",
         "V", "W2":  // ABI classes: V=Void (no retain), W2=String (handled by d2)
        return false
    case "W1":
        // W1 from Slot.from() — we don't know the concrete type.
        // Conservative: assume reference. Over-retaining leaks but doesn't crash.
        return true
    default:
        return true
    }
}
// MARK: - Dispatch Functions

@inline(__always)
private func rec(_ w: UnsafeRawPointer) -> StubRecorder { MockRegistry.resolve(w) }

/// Keeps dispatch results alive to prevent ARC from releasing reference-counted
/// values (Array, class refs) before the caller receives the raw bits.
/// Cleared periodically to avoid unbounded growth.
nonisolated(unsafe) private var _keepAlive: [Any] = []

/// W1 dispatch: 8-byte return.
/// Uses isRefReturn flag (from auto-discovery or slot metadata) to retain
/// reference types. Falls back to keepAlive for unknown cases.
@inline(__always)
private func d1(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) -> Int {
    let r = rec(w)
    let result = r.dispatch(method: m, args: a)
    if r.mode != .normal { return 0 }
    _keepAlive.append(result)
    if _keepAlive.count > 64 { _keepAlive.removeFirst(32) } // prevent unbounded growth
    let word = withUnsafePointer(to: result) { UnsafeRawPointer($0).load(as: Int.self) }
    if r.isRefReturn(m), let rawPtr = UnsafeRawPointer(bitPattern: word) {
        _ = Unmanaged<AnyObject>.fromOpaque(rawPtr).retain()
    }
    return word
}

/// W2 dispatch: String return.
@inline(__always)
private func d2(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) -> String {
    let r = rec(w)
    let result = r.dispatch(method: m, args: a)
    if r.mode != .normal { return "" }
    return result as! String
}

/// V dispatch: Void return.
@inline(__always)
private func dv(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) {
    let r = rec(w)
    _ = r.dispatch(method: m, args: a)
}
// MARK: - Getters (0-arg)

private let g_w1_0: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 0, []) }
private let g_w1_1: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 1, []) }
private let g_w1_2: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 2, []) }
private let g_w1_3: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 3, []) }
private let g_w1_4: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 4, []) }
private let g_w1_5: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 5, []) }
private let g_w1_6: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 6, []) }
private let g_w1_7: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 7, []) }
private let g_w1_8: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 8, []) }
private let g_w1_9: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 9, []) }
private let g_w1_10: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 10, []) }
private let g_w1_11: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 11, []) }
private let g_w1_12: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 12, []) }
private let g_w1_13: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 13, []) }
private let g_w1_14: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 14, []) }
private let g_w1_15: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Int = { _, w in d1(w, 15, []) }

private let g_w2_0: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 0, []) }
private let g_w2_1: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 1, []) }
private let g_w2_2: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 2, []) }
private let g_w2_3: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 3, []) }
private let g_w2_4: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 4, []) }
private let g_w2_5: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 5, []) }
private let g_w2_6: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 6, []) }
private let g_w2_7: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 7, []) }
private let g_w2_8: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 8, []) }
private let g_w2_9: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 9, []) }
private let g_w2_10: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 10, []) }
private let g_w2_11: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 11, []) }
private let g_w2_12: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 12, []) }
private let g_w2_13: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 13, []) }
private let g_w2_14: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 14, []) }
private let g_w2_15: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> String = { _, w in d2(w, 15, []) }

private let g_v_0: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 0, []) }
private let g_v_1: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 1, []) }
private let g_v_2: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 2, []) }
private let g_v_3: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 3, []) }
private let g_v_4: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 4, []) }
private let g_v_5: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 5, []) }
private let g_v_6: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 6, []) }
private let g_v_7: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 7, []) }
private let g_v_8: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 8, []) }
private let g_v_9: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 9, []) }
private let g_v_10: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 10, []) }
private let g_v_11: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 11, []) }
private let g_v_12: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 12, []) }
private let g_v_13: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 13, []) }
private let g_v_14: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 14, []) }
private let g_v_15: @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in dv(w, 15, []) }

// MARK: - 1-arg Methods

private let m1_w1w1_0: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 0, [a]) }
private let m1_w1w1_1: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 1, [a]) }
private let m1_w1w1_2: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 2, [a]) }
private let m1_w1w1_3: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 3, [a]) }
private let m1_w1w1_4: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 4, [a]) }
private let m1_w1w1_5: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 5, [a]) }
private let m1_w1w1_6: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 6, [a]) }
private let m1_w1w1_7: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 7, [a]) }
private let m1_w1w1_8: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 8, [a]) }
private let m1_w1w1_9: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 9, [a]) }
private let m1_w1w1_10: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 10, [a]) }
private let m1_w1w1_11: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 11, [a]) }
private let m1_w1w1_12: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 12, [a]) }
private let m1_w1w1_13: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 13, [a]) }
private let m1_w1w1_14: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 14, [a]) }
private let m1_w1w1_15: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 15, [a]) }

private let m1_w1w2_0: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 0, [a]) }
private let m1_w1w2_1: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 1, [a]) }
private let m1_w1w2_2: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 2, [a]) }
private let m1_w1w2_3: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 3, [a]) }
private let m1_w1w2_4: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 4, [a]) }
private let m1_w1w2_5: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 5, [a]) }
private let m1_w1w2_6: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 6, [a]) }
private let m1_w1w2_7: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 7, [a]) }
private let m1_w1w2_8: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 8, [a]) }
private let m1_w1w2_9: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 9, [a]) }
private let m1_w1w2_10: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 10, [a]) }
private let m1_w1w2_11: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 11, [a]) }
private let m1_w1w2_12: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 12, [a]) }
private let m1_w1w2_13: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 13, [a]) }
private let m1_w1w2_14: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 14, [a]) }
private let m1_w1w2_15: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 15, [a]) }

private let m1_w1v_0: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 0, [a]) }
private let m1_w1v_1: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 1, [a]) }
private let m1_w1v_2: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 2, [a]) }
private let m1_w1v_3: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 3, [a]) }
private let m1_w1v_4: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 4, [a]) }
private let m1_w1v_5: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 5, [a]) }
private let m1_w1v_6: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 6, [a]) }
private let m1_w1v_7: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 7, [a]) }
private let m1_w1v_8: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 8, [a]) }
private let m1_w1v_9: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 9, [a]) }
private let m1_w1v_10: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 10, [a]) }
private let m1_w1v_11: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 11, [a]) }
private let m1_w1v_12: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 12, [a]) }
private let m1_w1v_13: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 13, [a]) }
private let m1_w1v_14: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 14, [a]) }
private let m1_w1v_15: @convention(thin) (Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 15, [a]) }

private let m1_w2w1_0: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 0, [a]) }
private let m1_w2w1_1: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 1, [a]) }
private let m1_w2w1_2: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 2, [a]) }
private let m1_w2w1_3: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 3, [a]) }
private let m1_w2w1_4: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 4, [a]) }
private let m1_w2w1_5: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 5, [a]) }
private let m1_w2w1_6: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 6, [a]) }
private let m1_w2w1_7: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 7, [a]) }
private let m1_w2w1_8: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 8, [a]) }
private let m1_w2w1_9: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 9, [a]) }
private let m1_w2w1_10: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 10, [a]) }
private let m1_w2w1_11: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 11, [a]) }
private let m1_w2w1_12: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 12, [a]) }
private let m1_w2w1_13: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 13, [a]) }
private let m1_w2w1_14: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 14, [a]) }
private let m1_w2w1_15: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, _, w in d1(w, 15, [a]) }

private let m1_w2w2_0: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 0, [a]) }
private let m1_w2w2_1: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 1, [a]) }
private let m1_w2w2_2: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 2, [a]) }
private let m1_w2w2_3: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 3, [a]) }
private let m1_w2w2_4: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 4, [a]) }
private let m1_w2w2_5: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 5, [a]) }
private let m1_w2w2_6: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 6, [a]) }
private let m1_w2w2_7: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 7, [a]) }
private let m1_w2w2_8: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 8, [a]) }
private let m1_w2w2_9: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 9, [a]) }
private let m1_w2w2_10: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 10, [a]) }
private let m1_w2w2_11: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 11, [a]) }
private let m1_w2w2_12: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 12, [a]) }
private let m1_w2w2_13: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 13, [a]) }
private let m1_w2w2_14: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 14, [a]) }
private let m1_w2w2_15: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, _, w in d2(w, 15, [a]) }

private let m1_w2v_0: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 0, [a]) }
private let m1_w2v_1: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 1, [a]) }
private let m1_w2v_2: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 2, [a]) }
private let m1_w2v_3: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 3, [a]) }
private let m1_w2v_4: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 4, [a]) }
private let m1_w2v_5: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 5, [a]) }
private let m1_w2v_6: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 6, [a]) }
private let m1_w2v_7: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 7, [a]) }
private let m1_w2v_8: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 8, [a]) }
private let m1_w2v_9: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 9, [a]) }
private let m1_w2v_10: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 10, [a]) }
private let m1_w2v_11: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 11, [a]) }
private let m1_w2v_12: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 12, [a]) }
private let m1_w2v_13: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 13, [a]) }
private let m1_w2v_14: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 14, [a]) }
private let m1_w2v_15: @convention(thin) (String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in dv(w, 15, [a]) }

// MARK: - 2-arg Methods

private let m2_w1w1w1_0: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 0, [a, b]) }
private let m2_w1w1w1_1: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 1, [a, b]) }
private let m2_w1w1w1_2: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 2, [a, b]) }
private let m2_w1w1w1_3: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 3, [a, b]) }
private let m2_w1w1w1_4: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 4, [a, b]) }
private let m2_w1w1w1_5: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 5, [a, b]) }
private let m2_w1w1w1_6: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 6, [a, b]) }
private let m2_w1w1w1_7: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 7, [a, b]) }

private let m2_w1w1w2_0: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 0, [a, b]) }
private let m2_w1w1w2_1: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 1, [a, b]) }
private let m2_w1w1w2_2: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 2, [a, b]) }
private let m2_w1w1w2_3: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 3, [a, b]) }
private let m2_w1w1w2_4: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 4, [a, b]) }
private let m2_w1w1w2_5: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 5, [a, b]) }
private let m2_w1w1w2_6: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 6, [a, b]) }
private let m2_w1w1w2_7: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 7, [a, b]) }

private let m2_w1w1v_0: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 0, [a, b]) }
private let m2_w1w1v_1: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 1, [a, b]) }
private let m2_w1w1v_2: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 2, [a, b]) }
private let m2_w1w1v_3: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 3, [a, b]) }
private let m2_w1w1v_4: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 4, [a, b]) }
private let m2_w1w1v_5: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 5, [a, b]) }
private let m2_w1w1v_6: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 6, [a, b]) }
private let m2_w1w1v_7: @convention(thin) (Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 7, [a, b]) }

private let m2_w1w2w1_0: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 0, [a, b]) }
private let m2_w1w2w1_1: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 1, [a, b]) }
private let m2_w1w2w1_2: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 2, [a, b]) }
private let m2_w1w2w1_3: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 3, [a, b]) }
private let m2_w1w2w1_4: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 4, [a, b]) }
private let m2_w1w2w1_5: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 5, [a, b]) }
private let m2_w1w2w1_6: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 6, [a, b]) }
private let m2_w1w2w1_7: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 7, [a, b]) }

private let m2_w1w2w2_0: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 0, [a, b]) }
private let m2_w1w2w2_1: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 1, [a, b]) }
private let m2_w1w2w2_2: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 2, [a, b]) }
private let m2_w1w2w2_3: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 3, [a, b]) }
private let m2_w1w2w2_4: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 4, [a, b]) }
private let m2_w1w2w2_5: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 5, [a, b]) }
private let m2_w1w2w2_6: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 6, [a, b]) }
private let m2_w1w2w2_7: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 7, [a, b]) }

private let m2_w1w2v_0: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 0, [a, b]) }
private let m2_w1w2v_1: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 1, [a, b]) }
private let m2_w1w2v_2: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 2, [a, b]) }
private let m2_w1w2v_3: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 3, [a, b]) }
private let m2_w1w2v_4: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 4, [a, b]) }
private let m2_w1w2v_5: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 5, [a, b]) }
private let m2_w1w2v_6: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 6, [a, b]) }
private let m2_w1w2v_7: @convention(thin) (Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 7, [a, b]) }

private let m2_w2w1w1_0: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 0, [a, b]) }
private let m2_w2w1w1_1: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 1, [a, b]) }
private let m2_w2w1w1_2: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 2, [a, b]) }
private let m2_w2w1w1_3: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 3, [a, b]) }
private let m2_w2w1w1_4: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 4, [a, b]) }
private let m2_w2w1w1_5: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 5, [a, b]) }
private let m2_w2w1w1_6: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 6, [a, b]) }
private let m2_w2w1w1_7: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 7, [a, b]) }

private let m2_w2w1w2_0: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 0, [a, b]) }
private let m2_w2w1w2_1: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 1, [a, b]) }
private let m2_w2w1w2_2: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 2, [a, b]) }
private let m2_w2w1w2_3: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 3, [a, b]) }
private let m2_w2w1w2_4: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 4, [a, b]) }
private let m2_w2w1w2_5: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 5, [a, b]) }
private let m2_w2w1w2_6: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 6, [a, b]) }
private let m2_w2w1w2_7: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 7, [a, b]) }

private let m2_w2w1v_0: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 0, [a, b]) }
private let m2_w2w1v_1: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 1, [a, b]) }
private let m2_w2w1v_2: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 2, [a, b]) }
private let m2_w2w1v_3: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 3, [a, b]) }
private let m2_w2w1v_4: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 4, [a, b]) }
private let m2_w2w1v_5: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 5, [a, b]) }
private let m2_w2w1v_6: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 6, [a, b]) }
private let m2_w2w1v_7: @convention(thin) (String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 7, [a, b]) }

private let m2_w2w2w1_0: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 0, [a, b]) }
private let m2_w2w2w1_1: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 1, [a, b]) }
private let m2_w2w2w1_2: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 2, [a, b]) }
private let m2_w2w2w1_3: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 3, [a, b]) }
private let m2_w2w2w1_4: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 4, [a, b]) }
private let m2_w2w2w1_5: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 5, [a, b]) }
private let m2_w2w2w1_6: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 6, [a, b]) }
private let m2_w2w2w1_7: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, _, w in d1(w, 7, [a, b]) }

private let m2_w2w2w2_0: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 0, [a, b]) }
private let m2_w2w2w2_1: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 1, [a, b]) }
private let m2_w2w2w2_2: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 2, [a, b]) }
private let m2_w2w2w2_3: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 3, [a, b]) }
private let m2_w2w2w2_4: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 4, [a, b]) }
private let m2_w2w2w2_5: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 5, [a, b]) }
private let m2_w2w2w2_6: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 6, [a, b]) }
private let m2_w2w2w2_7: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, _, w in d2(w, 7, [a, b]) }

private let m2_w2w2v_0: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 0, [a, b]) }
private let m2_w2w2v_1: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 1, [a, b]) }
private let m2_w2w2v_2: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 2, [a, b]) }
private let m2_w2w2v_3: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 3, [a, b]) }
private let m2_w2w2v_4: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 4, [a, b]) }
private let m2_w2w2v_5: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 5, [a, b]) }
private let m2_w2w2v_6: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 6, [a, b]) }
private let m2_w2w2v_7: @convention(thin) (String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in dv(w, 7, [a, b]) }

// MARK: - 3-arg Methods

private let m3_w1w1w1w1_0: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w1w1w1w1_1: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w1w1w1w1_2: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w1w1w1w1_3: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w1w1w1w2_0: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w1w1w1w2_1: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w1w1w1w2_2: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w1w1w1w2_3: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w1w1w1v_0: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w1w1w1v_1: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w1w1w1v_2: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w1w1w1v_3: @convention(thin) (Int, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w1w1w2w1_0: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w1w1w2w1_1: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w1w1w2w1_2: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w1w1w2w1_3: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w1w1w2w2_0: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w1w1w2w2_1: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w1w1w2w2_2: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w1w1w2w2_3: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w1w1w2v_0: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w1w1w2v_1: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w1w1w2v_2: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w1w1w2v_3: @convention(thin) (Int, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w1w2w1w1_0: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w1w2w1w1_1: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w1w2w1w1_2: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w1w2w1w1_3: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w1w2w1w2_0: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w1w2w1w2_1: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w1w2w1w2_2: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w1w2w1w2_3: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w1w2w1v_0: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w1w2w1v_1: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w1w2w1v_2: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w1w2w1v_3: @convention(thin) (Int, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w1w2w2w1_0: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w1w2w2w1_1: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w1w2w2w1_2: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w1w2w2w1_3: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w1w2w2w2_0: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w1w2w2w2_1: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w1w2w2w2_2: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w1w2w2w2_3: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w1w2w2v_0: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w1w2w2v_1: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w1w2w2v_2: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w1w2w2v_3: @convention(thin) (Int, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w2w1w1w1_0: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w2w1w1w1_1: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w2w1w1w1_2: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w2w1w1w1_3: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w2w1w1w2_0: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w2w1w1w2_1: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w2w1w1w2_2: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w2w1w1w2_3: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w2w1w1v_0: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w2w1w1v_1: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w2w1w1v_2: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w2w1w1v_3: @convention(thin) (String, Int, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w2w1w2w1_0: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w2w1w2w1_1: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w2w1w2w1_2: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w2w1w2w1_3: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w2w1w2w2_0: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w2w1w2w2_1: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w2w1w2w2_2: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w2w1w2w2_3: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w2w1w2v_0: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w2w1w2v_1: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w2w1w2v_2: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w2w1w2v_3: @convention(thin) (String, Int, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w2w2w1w1_0: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w2w2w1w1_1: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w2w2w1w1_2: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w2w2w1w1_3: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w2w2w1w2_0: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w2w2w1w2_1: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w2w2w1w2_2: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w2w2w1w2_3: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w2w2w1v_0: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w2w2w1v_1: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w2w2w1v_2: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w2w2w1v_3: @convention(thin) (String, String, Int, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

private let m3_w2w2w2w1_0: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 0, [a, b, c]) }
private let m3_w2w2w2w1_1: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 1, [a, b, c]) }
private let m3_w2w2w2w1_2: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 2, [a, b, c]) }
private let m3_w2w2w2w1_3: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Int = { a, b, c, _, w in d1(w, 3, [a, b, c]) }

private let m3_w2w2w2w2_0: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 0, [a, b, c]) }
private let m3_w2w2w2w2_1: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 1, [a, b, c]) }
private let m3_w2w2w2w2_2: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 2, [a, b, c]) }
private let m3_w2w2w2w2_3: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> String = { a, b, c, _, w in d2(w, 3, [a, b, c]) }

private let m3_w2w2w2v_0: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 0, [a, b, c]) }
private let m3_w2w2w2v_1: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 1, [a, b, c]) }
private let m3_w2w2w2v_2: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 2, [a, b, c]) }
private let m3_w2w2w2v_3: @convention(thin) (String, String, String, UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in dv(w, 3, [a, b, c]) }

// MARK: - Thunk Catalog

public enum ThunkLibrary {
    nonisolated(unsafe) private static let catalog: [MethodSignature: [Int: UnsafeRawPointer]] = buildCatalog()

    /// Look up a thunk. Maps the signature to its ABI class first.
    public static func thunk(for signature: MethodSignature, slot: Int) -> UnsafeRawPointer? {
        catalog[signature.abiSignature]?[slot]
    }

    private static func buildCatalog() -> [MethodSignature: [Int: UnsafeRawPointer]] {
        var c = [MethodSignature: [Int: UnsafeRawPointer]]()
        func add(_ s: MethodSignature, _ slot: Int, _ p: UnsafeRawPointer) { c[s, default: [:]][slot] = p }
        func cast<T>(_ fn: T) -> UnsafeRawPointer { unsafeBitCast(fn, to: UnsafeRawPointer.self) }

        for (i, fn) in [g_w1_0, g_w1_1, g_w1_2, g_w1_3, g_w1_4, g_w1_5, g_w1_6, g_w1_7, g_w1_8, g_w1_9, g_w1_10, g_w1_11, g_w1_12, g_w1_13, g_w1_14, g_w1_15].enumerated() { add(MethodSignature.getter("W1"), i, cast(fn)) }
        for (i, fn) in [g_w2_0, g_w2_1, g_w2_2, g_w2_3, g_w2_4, g_w2_5, g_w2_6, g_w2_7, g_w2_8, g_w2_9, g_w2_10, g_w2_11, g_w2_12, g_w2_13, g_w2_14, g_w2_15].enumerated() { add(MethodSignature.getter("W2"), i, cast(fn)) }
        for (i, fn) in [g_v_0, g_v_1, g_v_2, g_v_3, g_v_4, g_v_5, g_v_6, g_v_7, g_v_8, g_v_9, g_v_10, g_v_11, g_v_12, g_v_13, g_v_14, g_v_15].enumerated() { add(MethodSignature.getter("V"), i, cast(fn)) }

        for (i, fn) in [m1_w1w1_0, m1_w1w1_1, m1_w1w1_2, m1_w1w1_3, m1_w1w1_4, m1_w1w1_5, m1_w1w1_6, m1_w1w1_7, m1_w1w1_8, m1_w1w1_9, m1_w1w1_10, m1_w1w1_11, m1_w1w1_12, m1_w1w1_13, m1_w1w1_14, m1_w1w1_15].enumerated() { add(MethodSignature(args: ["W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m1_w1w2_0, m1_w1w2_1, m1_w1w2_2, m1_w1w2_3, m1_w1w2_4, m1_w1w2_5, m1_w1w2_6, m1_w1w2_7, m1_w1w2_8, m1_w1w2_9, m1_w1w2_10, m1_w1w2_11, m1_w1w2_12, m1_w1w2_13, m1_w1w2_14, m1_w1w2_15].enumerated() { add(MethodSignature(args: ["W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m1_w1v_0, m1_w1v_1, m1_w1v_2, m1_w1v_3, m1_w1v_4, m1_w1v_5, m1_w1v_6, m1_w1v_7, m1_w1v_8, m1_w1v_9, m1_w1v_10, m1_w1v_11, m1_w1v_12, m1_w1v_13, m1_w1v_14, m1_w1v_15].enumerated() { add(MethodSignature(args: ["W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m1_w2w1_0, m1_w2w1_1, m1_w2w1_2, m1_w2w1_3, m1_w2w1_4, m1_w2w1_5, m1_w2w1_6, m1_w2w1_7, m1_w2w1_8, m1_w2w1_9, m1_w2w1_10, m1_w2w1_11, m1_w2w1_12, m1_w2w1_13, m1_w2w1_14, m1_w2w1_15].enumerated() { add(MethodSignature(args: ["W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m1_w2w2_0, m1_w2w2_1, m1_w2w2_2, m1_w2w2_3, m1_w2w2_4, m1_w2w2_5, m1_w2w2_6, m1_w2w2_7, m1_w2w2_8, m1_w2w2_9, m1_w2w2_10, m1_w2w2_11, m1_w2w2_12, m1_w2w2_13, m1_w2w2_14, m1_w2w2_15].enumerated() { add(MethodSignature(args: ["W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m1_w2v_0, m1_w2v_1, m1_w2v_2, m1_w2v_3, m1_w2v_4, m1_w2v_5, m1_w2v_6, m1_w2v_7, m1_w2v_8, m1_w2v_9, m1_w2v_10, m1_w2v_11, m1_w2v_12, m1_w2v_13, m1_w2v_14, m1_w2v_15].enumerated() { add(MethodSignature(args: ["W2"], ret: "V"), i, cast(fn)) }

        for (i, fn) in [m2_w1w1w1_0, m2_w1w1w1_1, m2_w1w1w1_2, m2_w1w1w1_3, m2_w1w1w1_4, m2_w1w1w1_5, m2_w1w1w1_6, m2_w1w1w1_7].enumerated() { add(MethodSignature(args: ["W1", "W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m2_w1w1w2_0, m2_w1w1w2_1, m2_w1w1w2_2, m2_w1w1w2_3, m2_w1w1w2_4, m2_w1w1w2_5, m2_w1w1w2_6, m2_w1w1w2_7].enumerated() { add(MethodSignature(args: ["W1", "W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m2_w1w1v_0, m2_w1w1v_1, m2_w1w1v_2, m2_w1w1v_3, m2_w1w1v_4, m2_w1w1v_5, m2_w1w1v_6, m2_w1w1v_7].enumerated() { add(MethodSignature(args: ["W1", "W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m2_w1w2w1_0, m2_w1w2w1_1, m2_w1w2w1_2, m2_w1w2w1_3, m2_w1w2w1_4, m2_w1w2w1_5, m2_w1w2w1_6, m2_w1w2w1_7].enumerated() { add(MethodSignature(args: ["W1", "W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m2_w1w2w2_0, m2_w1w2w2_1, m2_w1w2w2_2, m2_w1w2w2_3, m2_w1w2w2_4, m2_w1w2w2_5, m2_w1w2w2_6, m2_w1w2w2_7].enumerated() { add(MethodSignature(args: ["W1", "W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m2_w1w2v_0, m2_w1w2v_1, m2_w1w2v_2, m2_w1w2v_3, m2_w1w2v_4, m2_w1w2v_5, m2_w1w2v_6, m2_w1w2v_7].enumerated() { add(MethodSignature(args: ["W1", "W2"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m2_w2w1w1_0, m2_w2w1w1_1, m2_w2w1w1_2, m2_w2w1w1_3, m2_w2w1w1_4, m2_w2w1w1_5, m2_w2w1w1_6, m2_w2w1w1_7].enumerated() { add(MethodSignature(args: ["W2", "W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m2_w2w1w2_0, m2_w2w1w2_1, m2_w2w1w2_2, m2_w2w1w2_3, m2_w2w1w2_4, m2_w2w1w2_5, m2_w2w1w2_6, m2_w2w1w2_7].enumerated() { add(MethodSignature(args: ["W2", "W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m2_w2w1v_0, m2_w2w1v_1, m2_w2w1v_2, m2_w2w1v_3, m2_w2w1v_4, m2_w2w1v_5, m2_w2w1v_6, m2_w2w1v_7].enumerated() { add(MethodSignature(args: ["W2", "W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m2_w2w2w1_0, m2_w2w2w1_1, m2_w2w2w1_2, m2_w2w2w1_3, m2_w2w2w1_4, m2_w2w2w1_5, m2_w2w2w1_6, m2_w2w2w1_7].enumerated() { add(MethodSignature(args: ["W2", "W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m2_w2w2w2_0, m2_w2w2w2_1, m2_w2w2w2_2, m2_w2w2w2_3, m2_w2w2w2_4, m2_w2w2w2_5, m2_w2w2w2_6, m2_w2w2w2_7].enumerated() { add(MethodSignature(args: ["W2", "W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m2_w2w2v_0, m2_w2w2v_1, m2_w2w2v_2, m2_w2w2v_3, m2_w2w2v_4, m2_w2w2v_5, m2_w2w2v_6, m2_w2w2v_7].enumerated() { add(MethodSignature(args: ["W2", "W2"], ret: "V"), i, cast(fn)) }

        for (i, fn) in [m3_w1w1w1w1_0, m3_w1w1w1w1_1, m3_w1w1w1w1_2, m3_w1w1w1w1_3].enumerated() { add(MethodSignature(args: ["W1", "W1", "W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w1w1w1w2_0, m3_w1w1w1w2_1, m3_w1w1w1w2_2, m3_w1w1w1w2_3].enumerated() { add(MethodSignature(args: ["W1", "W1", "W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w1w1w1v_0, m3_w1w1w1v_1, m3_w1w1w1v_2, m3_w1w1w1v_3].enumerated() { add(MethodSignature(args: ["W1", "W1", "W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w1w1w2w1_0, m3_w1w1w2w1_1, m3_w1w1w2w1_2, m3_w1w1w2w1_3].enumerated() { add(MethodSignature(args: ["W1", "W1", "W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w1w1w2w2_0, m3_w1w1w2w2_1, m3_w1w1w2w2_2, m3_w1w1w2w2_3].enumerated() { add(MethodSignature(args: ["W1", "W1", "W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w1w1w2v_0, m3_w1w1w2v_1, m3_w1w1w2v_2, m3_w1w1w2v_3].enumerated() { add(MethodSignature(args: ["W1", "W1", "W2"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w1w2w1w1_0, m3_w1w2w1w1_1, m3_w1w2w1w1_2, m3_w1w2w1w1_3].enumerated() { add(MethodSignature(args: ["W1", "W2", "W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w1w2w1w2_0, m3_w1w2w1w2_1, m3_w1w2w1w2_2, m3_w1w2w1w2_3].enumerated() { add(MethodSignature(args: ["W1", "W2", "W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w1w2w1v_0, m3_w1w2w1v_1, m3_w1w2w1v_2, m3_w1w2w1v_3].enumerated() { add(MethodSignature(args: ["W1", "W2", "W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w1w2w2w1_0, m3_w1w2w2w1_1, m3_w1w2w2w1_2, m3_w1w2w2w1_3].enumerated() { add(MethodSignature(args: ["W1", "W2", "W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w1w2w2w2_0, m3_w1w2w2w2_1, m3_w1w2w2w2_2, m3_w1w2w2w2_3].enumerated() { add(MethodSignature(args: ["W1", "W2", "W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w1w2w2v_0, m3_w1w2w2v_1, m3_w1w2w2v_2, m3_w1w2w2v_3].enumerated() { add(MethodSignature(args: ["W1", "W2", "W2"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w2w1w1w1_0, m3_w2w1w1w1_1, m3_w2w1w1w1_2, m3_w2w1w1w1_3].enumerated() { add(MethodSignature(args: ["W2", "W1", "W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w2w1w1w2_0, m3_w2w1w1w2_1, m3_w2w1w1w2_2, m3_w2w1w1w2_3].enumerated() { add(MethodSignature(args: ["W2", "W1", "W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w2w1w1v_0, m3_w2w1w1v_1, m3_w2w1w1v_2, m3_w2w1w1v_3].enumerated() { add(MethodSignature(args: ["W2", "W1", "W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w2w1w2w1_0, m3_w2w1w2w1_1, m3_w2w1w2w1_2, m3_w2w1w2w1_3].enumerated() { add(MethodSignature(args: ["W2", "W1", "W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w2w1w2w2_0, m3_w2w1w2w2_1, m3_w2w1w2w2_2, m3_w2w1w2w2_3].enumerated() { add(MethodSignature(args: ["W2", "W1", "W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w2w1w2v_0, m3_w2w1w2v_1, m3_w2w1w2v_2, m3_w2w1w2v_3].enumerated() { add(MethodSignature(args: ["W2", "W1", "W2"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w2w2w1w1_0, m3_w2w2w1w1_1, m3_w2w2w1w1_2, m3_w2w2w1w1_3].enumerated() { add(MethodSignature(args: ["W2", "W2", "W1"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w2w2w1w2_0, m3_w2w2w1w2_1, m3_w2w2w1w2_2, m3_w2w2w1w2_3].enumerated() { add(MethodSignature(args: ["W2", "W2", "W1"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w2w2w1v_0, m3_w2w2w1v_1, m3_w2w2w1v_2, m3_w2w2w1v_3].enumerated() { add(MethodSignature(args: ["W2", "W2", "W1"], ret: "V"), i, cast(fn)) }
        for (i, fn) in [m3_w2w2w2w1_0, m3_w2w2w2w1_1, m3_w2w2w2w1_2, m3_w2w2w2w1_3].enumerated() { add(MethodSignature(args: ["W2", "W2", "W2"], ret: "W1"), i, cast(fn)) }
        for (i, fn) in [m3_w2w2w2w2_0, m3_w2w2w2w2_1, m3_w2w2w2w2_2, m3_w2w2w2w2_3].enumerated() { add(MethodSignature(args: ["W2", "W2", "W2"], ret: "W2"), i, cast(fn)) }
        for (i, fn) in [m3_w2w2w2v_0, m3_w2w2w2v_1, m3_w2w2w2v_2, m3_w2w2w2v_3].enumerated() { add(MethodSignature(args: ["W2", "W2", "W2"], ret: "V"), i, cast(fn)) }

        return c
    }
}


