#!/bin/bash

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_path="${SWIFT_TEST_DOUBLES_API_BUILD_PATH:-$root/.build/public-api-validation}"
symbol_build_path="${SWIFT_TEST_DOUBLES_SYMBOL_GRAPH_BUILD_PATH:-$root/.build/symbol-graph-validation}"
raw_symbols="$symbol_build_path/symbols"
generated="$build_path/PUBLIC_API.snapshot"
snapshot="$root/PUBLIC_API.snapshot"
mode="${1:-}"

if [[ -n "$mode" && "$mode" != "--update" ]]; then
    echo "usage: Scripts/check-public-api.sh [--update]" >&2
    exit 64
fi

cd "$root"
mkdir -p "$build_path"
SWIFT_TEST_DOUBLES_SYMBOL_GRAPH_BUILD_PATH="$symbol_build_path" \
    Scripts/generate-symbol-graph.sh

ruby -rjson - "$raw_symbols/TestDoubles.symbols.json" > "$generated" <<'RUBY'
graph = JSON.parse(File.read(ARGV.fetch(0)))
symbols = graph.fetch("symbols")
symbols_by_identifier = symbols.to_h do |symbol|
  [symbol.fetch("identifier").fetch("precise"), symbol]
end

entries = symbols.each_with_object([]) do |symbol, result|
  next if symbol.fetch("identifier").fetch("precise").include?("::SYNTHESIZED::")

  kind = symbol.fetch("kind").fetch("identifier")
  path = symbol.fetch("pathComponents").join(".")
  declaration = symbol.fetch("declarationFragments").map do |fragment|
    fragment.fetch("spelling")
  end.join.gsub(/\s+/, " ").strip
  result << "symbol\t#{kind}\t#{path}\t#{declaration}"

  symbol.fetch("availability", []).each do |availability|
    normalized = availability.keys.sort.to_h do |key|
      value = availability.fetch(key)
      value = value.keys.sort.to_h { |nested_key| [nested_key, value.fetch(nested_key)] } if value.is_a?(Hash)
      [key, value]
    end
    result << "availability\t#{path}\t#{JSON.generate(normalized)}"
  end
end

graph.fetch("relationships").each do |relationship|
  next unless relationship.fetch("kind") == "conformsTo"

  source = symbols_by_identifier[relationship.fetch("source")]
  next unless source

  target = relationship["targetFallback"] || relationship.fetch("target")
  next if target == "Swift.SendableMetatype"

  constraints = relationship.fetch("swiftConstraints", []).map do |constraint|
    constraint.keys.sort.to_h { |key| [key, constraint.fetch(key)] }
  end.sort_by { |constraint| JSON.generate(constraint) }
  entries << "conformance\t#{source.fetch("pathComponents").join(".")}\t#{target}\t#{JSON.generate(constraints)}"
end

puts "# Generated by Scripts/check-public-api.sh; do not edit by hand."
puts "# Format: symbol <kind> <path> <declaration>, including public conformances."
puts entries.sort
RUBY

if [[ "$mode" == "--update" ]]; then
    cp "$generated" "$snapshot"
    echo "Updated PUBLIC_API.snapshot"
    exit 0
fi

if [[ ! -f "$snapshot" ]]; then
    echo "PUBLIC_API.snapshot is missing; run Scripts/check-public-api.sh --update" >&2
    exit 1
fi

if ! cmp -s "$snapshot" "$generated"; then
    diff -u "$snapshot" "$generated" || true
    echo "Public API changed; review it, update the public API documentation, then run Scripts/check-public-api.sh --update" >&2
    exit 1
fi

echo "Public API snapshot matches."
