#!/usr/bin/env swift
//
// Generates ThunkLibrary.swift with all ABI-class thunk combinations.
//
// ABI classes:
//   W1 (Int)    — all 8-byte types: Int, Bool, Double, Array, class refs, custom structs
//   W2 (String) — 16-byte types: String
//   V  (Void)   — void return / void methods
//
// For each (arg_classes..., return_class) × slot_index, generates one
// @convention(thin) thunk that dispatches through the registry.
//
// Usage: swift Scripts/generate_thunks.swift > Sources/TestDoubles/ThunkLibrary.generated.swift

let maxSlots = 16

// ABI classes with their Swift type representation
struct ABI: CustomStringConvertible {
    let id: String      // "W1", "W2", "V"
    let swiftType: String  // "Int", "String", "Void"
    var description: String { id }
}

let W1 = ABI(id: "W1", swiftType: "Int")
let FX = ABI(id: "FX", swiftType: "Double")
let W2 = ABI(id: "W2", swiftType: "String")
let V  = ABI(id: "V",  swiftType: "Void")

let argClasses = [W1, FX, W2]  // V not used as arg
let retClasses = [W1, FX, W2, V]

// Slot counts per arity (higher arities get fewer slots to keep file size reasonable)
let slotsForArity: [Int: Int] = [
    0: maxSlots,   // getters: 16 slots
    1: 8,          // 1-arg: 8 slots
    2: 4,          // 2-arg: 4 slots
    3: 2,          // 3-arg: 2 slots
]

var output = ""
func emit(_ s: String = "") { output += s + "\n" }

// MARK: - Header

emit("// Auto-generated by Scripts/generate_thunks.swift — DO NOT EDIT")
emit("//")
emit("// ABI-class thunks for witness table patching.")
emit("// W1 = 8-byte (Int, Bool, Double, Array, class refs, custom structs)")
emit("// W2 = 16-byte (String)")
emit("// V  = Void")
emit("//")
emit("// Thunks: \\(totalThunks) total across 0-3 arg arities.")
emit("")
emit("import Foundation")
emit("")

// MARK: - MethodSignature

emit("""
/// Describes a method signature for thunk lookup.
public struct MethodSignature: Hashable, Sendable {
    public let args: [String]
    public let ret: String

    public init(args: [String], ret: String) {
        self.args = args
        self.ret = ret
    }

    public static func getter(_ type: String) -> MethodSignature { .init(args: [], ret: type) }
    public static func method(_ args: [String], returning ret: String) -> MethodSignature { .init(args: args, ret: ret) }

    /// Maps this signature to its ABI-class equivalent for thunk lookup.
    var abiSignature: MethodSignature {
        MethodSignature(args: args.map(argABI), ret: retABI(ret))
    }
}
""")

// MARK: - ABI mapping functions

emit("""
private func argABI(_ typeName: String) -> String {
    switch typeName {
    case "W1", "W2", "FX": return typeName
    case "String": return "W2"
    case "Double", "Float": return "FX"
    default: return "W1"
    }
}

private func retABI(_ typeName: String) -> String {
    switch typeName {
    case "W1", "W2", "FX", "V": return typeName
    case "Void": return "V"
    case "String": return "W2"
    case "Double", "Float": return "FX"
    default: return "W1"
    }
}

/// Determines if a return type needs ARC retain when returned as raw bits.
func isReferenceReturn(_ typeName: String) -> Bool {
    switch typeName {
    case "Int", "Bool", "Double", "Float", "String", "Void",
         "UInt", "Int8", "Int16", "Int32", "Int64",
         "UInt8", "UInt16", "UInt32", "UInt64",
         "V", "W2", "FX":
        return false
    default:
        return true
    }
}
""")

// MARK: - Dispatch functions

emit("""
// MARK: - Dispatch Functions

@inline(__always)
private func rec(_ w: UnsafeRawPointer) -> StubRecorder { MockRegistry.resolve(w) }

/// Thread-local keepalive for dispatch results.
private let _keepAliveKey = "_TestDoubles_keepAlive"
private func keepAlive(_ value: Any) {
    var arr = Thread.current.threadDictionary[_keepAliveKey] as? [Any] ?? []
    arr.append(value)
    if arr.count > 32 { arr.removeFirst(16) }
    Thread.current.threadDictionary[_keepAliveKey] = arr
}

/// W1 dispatch: 8-byte integer-register return.
@inline(__always)
private func d1(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) -> Int {
    let r = rec(w)
    let result = r.dispatch(method: m, args: a)
    if r.mode != .normal { return 0 }
    keepAlive(result)
    let word = withUnsafePointer(to: result) { UnsafeRawPointer($0).load(as: Int.self) }
    if r.isRefReturn(m), let rawPtr = UnsafeRawPointer(bitPattern: word) {
        _ = Unmanaged<AnyObject>.fromOpaque(rawPtr).retain()
    }
    return word
}

/// FX dispatch: 8-byte SIMD-register return (Double, Float).
@inline(__always)
private func df(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) -> Double {
    let r = rec(w)
    let result = r.dispatch(method: m, args: a)
    if r.mode != .normal { return 0.0 }
    return withUnsafePointer(to: result) { UnsafeRawPointer($0).load(as: Double.self) }
}

/// W2 dispatch: String return.
@inline(__always)
private func d2(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) -> String {
    let r = rec(w)
    let result = r.dispatch(method: m, args: a)
    if r.mode != .normal { return "" }
    return result as! String
}

/// V dispatch: Void return.
@inline(__always)
private func dv(_ w: UnsafeRawPointer, _ m: Int, _ a: [Any]) {
    let r = rec(w)
    _ = r.dispatch(method: m, args: a)
}
""")

// MARK: - Thunk generation

var totalThunks = 0

func dispatchCall(ret: ABI, slot: String, args: String) -> String {
    switch ret.id {
    case "W1": return "d1(w, \(slot), \(args))"
    case "FX": return "df(w, \(slot), \(args))"
    case "W2": return "d2(w, \(slot), \(args))"
    case "V":  return "dv(w, \(slot), \(args))"
    default: fatalError()
    }
}

func retArrow(_ ret: ABI) -> String {
    ret.id == "V" ? "Void" : ret.swiftType
}

// --- Getters (0-arg) ---

emit("// MARK: - Getters (0-arg)")
emit("")

for ret in retClasses {
    let slots = slotsForArity[0]!
    for s in 0..<slots {
        let name = "g_\(ret.id.lowercased())_\(s)"
        let call = dispatchCall(ret: ret, slot: "\(s)", args: "[]")
        if ret.id == "V" {
            emit("private let \(name): @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> Void = { _, w in \(call) }")
        } else {
            emit("private let \(name): @convention(thin) (UnsafeRawPointer, UnsafeRawPointer) -> \(ret.swiftType) = { _, w in \(call) }")
        }
        totalThunks += 1
    }
    emit("")
}

// --- 1-arg methods ---

emit("// MARK: - 1-arg Methods")
emit("")

for arg in argClasses {
    for ret in retClasses {
        let slots = slotsForArity[1]!
        for s in 0..<slots {
            let name = "m1_\(arg.id.lowercased())\(ret.id.lowercased())_\(s)"
            let argList = "[a]"
            let call = dispatchCall(ret: ret, slot: "\(s)", args: argList)
            if ret.id == "V" {
                emit("private let \(name): @convention(thin) (\(arg.swiftType), UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, _, w in \(call) }")
            } else {
                emit("private let \(name): @convention(thin) (\(arg.swiftType), UnsafeRawPointer, UnsafeRawPointer) -> \(ret.swiftType) = { a, _, w in \(call) }")
            }
            totalThunks += 1
        }
        emit("")
    }
}

// --- 2-arg methods ---

emit("// MARK: - 2-arg Methods")
emit("")

for arg1 in argClasses {
    for arg2 in argClasses {
        for ret in retClasses {
            let slots = slotsForArity[2]!
            for s in 0..<slots {
                let name = "m2_\(arg1.id.lowercased())\(arg2.id.lowercased())\(ret.id.lowercased())_\(s)"
                let argList = "[a, b]"
                let call = dispatchCall(ret: ret, slot: "\(s)", args: argList)
                if ret.id == "V" {
                    emit("private let \(name): @convention(thin) (\(arg1.swiftType), \(arg2.swiftType), UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, _, w in \(call) }")
                } else {
                    emit("private let \(name): @convention(thin) (\(arg1.swiftType), \(arg2.swiftType), UnsafeRawPointer, UnsafeRawPointer) -> \(ret.swiftType) = { a, b, _, w in \(call) }")
                }
                totalThunks += 1
            }
            emit("")
        }
    }
}

// --- 3-arg methods ---

emit("// MARK: - 3-arg Methods")
emit("")

for arg1 in argClasses {
    for arg2 in argClasses {
        for arg3 in argClasses {
            for ret in retClasses {
                let slots = slotsForArity[3]!
                for s in 0..<slots {
                    let name = "m3_\(arg1.id.lowercased())\(arg2.id.lowercased())\(arg3.id.lowercased())\(ret.id.lowercased())_\(s)"
                    let argList = "[a, b, c]"
                    let call = dispatchCall(ret: ret, slot: "\(s)", args: argList)
                    if ret.id == "V" {
                        emit("private let \(name): @convention(thin) (\(arg1.swiftType), \(arg2.swiftType), \(arg3.swiftType), UnsafeRawPointer, UnsafeRawPointer) -> Void = { a, b, c, _, w in \(call) }")
                    } else {
                        emit("private let \(name): @convention(thin) (\(arg1.swiftType), \(arg2.swiftType), \(arg3.swiftType), UnsafeRawPointer, UnsafeRawPointer) -> \(ret.swiftType) = { a, b, c, _, w in \(call) }")
                    }
                    totalThunks += 1
                }
                emit("")
            }
        }
    }
}

// MARK: - Catalog

emit("// MARK: - Thunk Catalog")
emit("")
emit("public enum ThunkLibrary {")
emit("    nonisolated(unsafe) private static let catalog: [MethodSignature: [Int: UnsafeRawPointer]] = buildCatalog()")
emit("")
emit("    /// Look up a thunk. Maps the signature to its ABI class first.")
emit("    public static func thunk(for signature: MethodSignature, slot: Int) -> UnsafeRawPointer? {")
emit("        catalog[signature.abiSignature]?[slot]")
emit("    }")
emit("")
emit("    private static func buildCatalog() -> [MethodSignature: [Int: UnsafeRawPointer]] {")
emit("        var c = [MethodSignature: [Int: UnsafeRawPointer]]()")
emit("        func add(_ s: MethodSignature, _ slot: Int, _ p: UnsafeRawPointer) { c[s, default: [:]][slot] = p }")
emit("        func cast<T>(_ fn: T) -> UnsafeRawPointer { unsafeBitCast(fn, to: UnsafeRawPointer.self) }")
emit("")

// Getters
for ret in retClasses {
    let sig = "MethodSignature.getter(\"\(ret.id)\")"
    let slots = slotsForArity[0]!
    let names = (0..<slots).map { "g_\(ret.id.lowercased())_\($0)" }
    emit("        for (i, fn) in [\(names.joined(separator: ", "))].enumerated() { add(\(sig), i, cast(fn)) }")
}
emit("")

// 1-arg
for arg in argClasses {
    for ret in retClasses {
        let sig = "MethodSignature(args: [\"\(arg.id)\"], ret: \"\(ret.id)\")"
        let slots = slotsForArity[1]!
        let names = (0..<slots).map { "m1_\(arg.id.lowercased())\(ret.id.lowercased())_\($0)" }
        emit("        for (i, fn) in [\(names.joined(separator: ", "))].enumerated() { add(\(sig), i, cast(fn)) }")
    }
}
emit("")

// 2-arg
for arg1 in argClasses {
    for arg2 in argClasses {
        for ret in retClasses {
            let sig = "MethodSignature(args: [\"\(arg1.id)\", \"\(arg2.id)\"], ret: \"\(ret.id)\")"
            let slots = slotsForArity[2]!
            let names = (0..<slots).map { "m2_\(arg1.id.lowercased())\(arg2.id.lowercased())\(ret.id.lowercased())_\($0)" }
            emit("        for (i, fn) in [\(names.joined(separator: ", "))].enumerated() { add(\(sig), i, cast(fn)) }")
        }
    }
}
emit("")

// 3-arg
for arg1 in argClasses {
    for arg2 in argClasses {
        for arg3 in argClasses {
            for ret in retClasses {
                let sig = "MethodSignature(args: [\"\(arg1.id)\", \"\(arg2.id)\", \"\(arg3.id)\"], ret: \"\(ret.id)\")"
                let slots = slotsForArity[3]!
                let names = (0..<slots).map { "m3_\(arg1.id.lowercased())\(arg2.id.lowercased())\(arg3.id.lowercased())\(ret.id.lowercased())_\($0)" }
                emit("        for (i, fn) in [\(names.joined(separator: ", "))].enumerated() { add(\(sig), i, cast(fn)) }")
            }
        }
    }
}

emit("")
emit("        return c")
emit("    }")
emit("}")
emit("")

// Fix the total count in the header
output = output.replacingOccurrences(of: "\\(totalThunks)", with: "\(totalThunks)")

print(output)

// Print stats to stderr
import Foundation
FileHandle.standardError.write("Generated \(totalThunks) thunks\n".data(using: .utf8)!)
