// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

enum BuiltInFoundationValueCatalog {
    static func placeholder(for type: Any.Type) -> Any? {
        switch type {
            case is URL.Type:
                URL(filePath: "/test-doubles-placeholder")
            case is Data.Type:
                Data([0x54, 0x44])
            case is Date.Type:
                Date(timeIntervalSinceReferenceDate: 1)
            case is UUID.Type:
                UUID(uuidString: "54455354-444F-5542-4C45-530000000001")
            case is Calendar.Type:
                Calendar(identifier: .gregorian)
            case is Locale.Type:
                Locale(identifier: "en_US_POSIX")
            case is TimeZone.Type:
                TimeZone(secondsFromGMT: 0)
            case is IndexPath.Type:
                IndexPath(index: 0)
            case is IndexSet.Type:
                IndexSet(integer: 0)
            case is DateInterval.Type:
                DateInterval(start: Date(timeIntervalSinceReferenceDate: 1), duration: 1)
            case is CharacterSet.Type:
                CharacterSet(charactersIn: "A")
            case is Decimal.Type:
                Decimal(1)
            case is Notification.Name.Type:
                Notification.Name("TestDoubles.Placeholder")
            case is Notification.Type:
                Notification(name: Notification.Name("TestDoubles.Placeholder"))
            case is AttributedString.Type:
                AttributedString("test-doubles-placeholder")
            case is PersonNameComponents.Type:
                personNameComponents()
            #if canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))
                case is URLRequest.Type:
                    URLRequest(url: URL(filePath: "/test-doubles-placeholder"))
            #endif
            default:
                nil
        }
    }

    private static func personNameComponents() -> PersonNameComponents {
        var components = PersonNameComponents()
        components.givenName = "Test"
        components.familyName = "Doubles"
        return components
    }
}

extension BuiltInResultAdapters {
    static func appendFoundationAdapters(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        appendURL(to: &adapters)
        appendData(to: &adapters)
        appendDate(to: &adapters)
        appendUUID(to: &adapters)
        appendCalendar(to: &adapters)
        appendLocale(to: &adapters)
        appendTimeZone(to: &adapters)
        appendIndexPath(to: &adapters)
        appendIndexSet(to: &adapters)
        appendDateInterval(to: &adapters)
        appendCharacterSet(to: &adapters)
        appendDecimal(to: &adapters)
        appendNotificationName(to: &adapters)
        appendNotification(to: &adapters)
        appendAttributedString(to: &adapters)
        appendPersonNameComponents(to: &adapters)
        #if canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))
            appendURLRequest(to: &adapters)
        #endif
    }

    private static func appendURL(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> URL =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> URL =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> URL =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> URL =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: URL.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendData(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Data =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Data =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Data =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Data =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Data.self,
            resultTransport: .direct,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendDate(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Date =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Date =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Date =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Date =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Date.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendUUID(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> UUID =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> UUID =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> UUID =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> UUID =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: UUID.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendCalendar(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Calendar =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Calendar =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Calendar =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Calendar =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Calendar.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendLocale(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Locale =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Locale =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Locale =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Locale =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Locale.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendTimeZone(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> TimeZone =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> TimeZone =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> TimeZone =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> TimeZone =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: TimeZone.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendIndexPath(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> IndexPath =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> IndexPath =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> IndexPath =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> IndexPath =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: IndexPath.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendIndexSet(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> IndexSet =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> IndexSet =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> IndexSet =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> IndexSet =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: IndexSet.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendDateInterval(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> DateInterval =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> DateInterval =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> DateInterval =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> DateInterval =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: DateInterval.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendCharacterSet(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> CharacterSet =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> CharacterSet =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> CharacterSet =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> CharacterSet =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: CharacterSet.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendDecimal(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Decimal =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Decimal =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Decimal =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Decimal =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Decimal.self,
            resultTransport: .direct,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendNotificationName(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Notification.Name =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Notification.Name =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Notification.Name =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Notification.Name =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Notification.Name.self,
            resultTransport: .direct,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendNotification(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> Notification =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> Notification =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> Notification =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> Notification =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: Notification.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendAttributedString(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> AttributedString =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> AttributedString =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> AttributedString =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> AttributedString =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: AttributedString.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    private static func appendPersonNameComponents(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        let synchronous: @convention(thin) (BuiltInResultInvocation) -> PersonNameComponents =
            { invocation in invocation.call() }
        let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> PersonNameComponents =
            { invocation in try invocation.callThrowing() }
        let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> PersonNameComponents =
            { invocation in await invocation.call() }
        let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> PersonNameComponents =
            { invocation in try await invocation.callThrowing() }
        append(
            returning: PersonNameComponents.self,
            resultTransport: .indirect,
            synchronous: token(for: synchronous),
            synchronousThrowing: token(for: synchronousThrowing),
            asynchronous: token(for: asynchronous),
            asynchronousThrowing: token(for: asynchronousThrowing),
            to: &adapters
        )
    }

    #if canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))
        private static func appendURLRequest(
            to adapters: inout [RuntimeAutomaticRequirementAdapter]
        ) {
            let synchronous: @convention(thin) (BuiltInResultInvocation) -> URLRequest =
                { invocation in invocation.call() }
            let synchronousThrowing: @convention(thin) (BuiltInResultInvocation) throws -> URLRequest =
                { invocation in try invocation.callThrowing() }
            let asynchronous: @convention(thin) (BuiltInResultInvocation) async -> URLRequest =
                { invocation in await invocation.call() }
            let asynchronousThrowing: @convention(thin) (BuiltInResultInvocation) async throws -> URLRequest =
                { invocation in try await invocation.callThrowing() }
            append(
                returning: URLRequest.self,
                resultTransport: .indirect,
                synchronous: token(for: synchronous),
                synchronousThrowing: token(for: synchronousThrowing),
                asynchronous: token(for: asynchronous),
                asynchronousThrowing: token(for: asynchronousThrowing),
                to: &adapters
            )
        }
    #endif
}
