// Generated by Scripts/generate-built-in-result-adapters.swift; do not edit by hand.

import Foundation
#if canImport(FoundationNetworking) && !os(Android)
    import FoundationNetworking
#endif
import InternalRuntimeContract

enum BuiltInFoundationValueCatalog {
    static func placeholder(for type: Any.Type) -> Any? {
        switch type {
            case is URL.Type:
                URL(filePath: "/test-doubles-placeholder")
            case is Data.Type:
                Data([0x54, 0x44])
            case is Date.Type:
                Date(timeIntervalSinceReferenceDate: 1)
            case is UUID.Type:
                UUID(uuidString: "54455354-444F-5542-4C45-530000000001")
            case is Calendar.Type:
                Calendar(identifier: .gregorian)
            case is Locale.Type:
                Locale(identifier: "en_US_POSIX")
            case is TimeZone.Type:
                TimeZone(secondsFromGMT: 0)
            case is IndexPath.Type:
                IndexPath(index: 0)
            case is IndexSet.Type:
                IndexSet(integer: 0)
            case is DateInterval.Type:
                DateInterval(start: Date(timeIntervalSinceReferenceDate: 1), duration: 1)
            case is CharacterSet.Type:
                CharacterSet(charactersIn: "A")
            case is Decimal.Type:
                Decimal(1)
            case is Notification.Name.Type:
                Notification.Name("TestDoubles.Placeholder")
            case is Notification.Type:
                Notification(name: Notification.Name("TestDoubles.Placeholder"))
            case is AttributedString.Type:
                AttributedString("test-doubles-placeholder")
            case is PersonNameComponents.Type:
                personNameComponents()
            #if canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))
                case is URLRequest.Type:
                    URLRequest(url: URL(filePath: "/test-doubles-placeholder"))
            #endif
            default:
                nil
        }
    }

    private static func personNameComponents() -> PersonNameComponents {
        var components = PersonNameComponents()
        components.givenName = "Test"
        components.familyName = "Doubles"
        return components
    }
}

extension BuiltInResultAdapters {
    static func appendFoundationAdapters(
        to adapters: inout [RuntimeAutomaticRequirementAdapter]
    ) {
        #if (!os(WASI)) && compiler(>=6.4)
            appendURL(to: &adapters)
        #endif
        #if !os(WASI)
            appendData(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendDate(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendUUID(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendCalendar(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendLocale(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendTimeZone(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendIndexPath(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendIndexSet(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendDateInterval(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendCharacterSet(to: &adapters)
        #endif
        #if !os(WASI)
            appendDecimal(to: &adapters)
        #endif
        #if !os(WASI)
            appendNotificationName(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendNotification(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendAttributedString(to: &adapters)
        #endif
        #if (!os(WASI)) && compiler(>=6.4)
            appendPersonNameComponents(to: &adapters)
        #endif
        #if ((canImport(Darwin) || (canImport(FoundationNetworking) && !os(Android))) && !os(WASI)) && compiler(>=6.4)
            appendURLRequest(to: &adapters)
        #endif
    }
}
