// Generated by Scripts/generate-fixed-arity.swift; do not edit by hand.
// Swift cannot reabstract an unbound method reference through a parameter-pack
// function parameter. Keep these convenience overloads at fixed arities; the
// explicit metatype-based factory continues to support arbitrary arity.
extension Stub.Requirement {
    /// Infers a synchronous zero-argument method requirement from a protocol method reference.
    public static func method<Result>(
        signatureOf method: (_ instance: P) -> () -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing zero-argument method requirement from a protocol method reference.
    public static func method<Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> () throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous zero-argument method requirement from a protocol method reference.
    public static func method<Result>(
        signatureOf method: (_ instance: P) -> () async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing zero-argument method requirement from a protocol method reference.
    public static func method<Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> () async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }

    /// Infers a synchronous one-argument method requirement from a protocol method reference.
    public static func method<A0, Result>(
        signatureOf method: (_ instance: P) -> (A0) -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing one-argument method requirement from a protocol method reference.
    public static func method<A0, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0) throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous one-argument method requirement from a protocol method reference.
    public static func method<A0, Result>(
        signatureOf method: (_ instance: P) -> (A0) async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing one-argument method requirement from a protocol method reference.
    public static func method<A0, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0) async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }

    /// Infers a synchronous two-argument method requirement from a protocol method reference.
    public static func method<A0, A1, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1) -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing two-argument method requirement from a protocol method reference.
    public static func method<A0, A1, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1) throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous two-argument method requirement from a protocol method reference.
    public static func method<A0, A1, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1) async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing two-argument method requirement from a protocol method reference.
    public static func method<A0, A1, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1) async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }

    /// Infers a synchronous three-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2) -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing three-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2) throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous three-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2) async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing three-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2) async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }

    /// Infers a synchronous four-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3) -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing four-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3) throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous four-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3) async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing four-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3) async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }

    /// Infers a synchronous five-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4) -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing five-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4) throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous five-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4) async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing five-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4) async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }

    /// Infers a synchronous six-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, A5, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4, A5) -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self, A5.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: false
        )
    }

    /// Infers a synchronous throwing six-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, A5, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4, A5) throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self, A5.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: false
        )
    }

    /// Infers an asynchronous six-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, A5, Result>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4, A5) async -> Result
    ) -> Self {
        _ = method
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self, A5.self],
            returning: Result.self,
            isThrowing: false,
            isAsync: true
        )
    }

    /// Infers an asynchronous throwing six-argument method requirement from a protocol method reference.
    public static func method<A0, A1, A2, A3, A4, A5, Result, Failure: Error>(
        signatureOf method: (_ instance: P) -> (A0, A1, A2, A3, A4, A5) async throws(Failure) -> Result
    ) -> Self {
        _ = method
        let effect = inferredThrowingEffect(for: Failure.self)
        return inferredMethod(
            arguments: [A0.self, A1.self, A2.self, A3.self, A4.self, A5.self],
            returning: Result.self,
            typedErrorType: effect.typedErrorType,
            isThrowing: effect.isThrowing,
            isAsync: true
        )
    }
}
